# Generated by Django 4.2.2 on 2023-07-04 17:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WebsiteProperty',
            fields=[
                ('key', models.CharField(editable=False, max_length=100, primary_key=True, serialize=False, unique=True)),
                ('value', models.CharField(blank=True, help_text='Comma-separated list of values', max_length=1000, validators=[django.core.validators.RegexValidator('^[^\\,]+(?:\\,[^\\,]+)*$')])),
                ('description', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Website Property',
                'verbose_name_plural': 'Website Properties',
            },
        ),
    ]
