# Generated by Django 5.2.5 on 2025-08-21 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='websiteproperty',
            options={'ordering': ['key'], 'verbose_name': 'Website Property', 'verbose_name_plural': 'Website Properties'},
        ),
    ]
