apiVersion: batch/v1
kind: Job
metadata:
  name: spellbook-migration
  namespace: spellbook-prod
spec:
  template:
    spec:
      serviceAccountName: app-service-account
      containers:
      - name: spellbook-migration
        image: 083767677168.dkr.ecr.us-east-2.amazonaws.com/spellbook-prod-ecr
        command: ["/bin/sh", "-c"]
        args: ["python manage.py migrate --noinput && python manage.py seed_website_properties && python manage.py clean_jobs"]
        env:
          - name: SECRET_KEY
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: django-secret
          - name: KUBE_SQL_ENGINE
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-engine
          - name: KUBE_SQL_DATABASE
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-name
          - name: KUBE_SQL_USER
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-user
          - name: KUBE_SQL_PASSWORD
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-password
          - name: KUBE_SQL_HOST
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-host
          - name: KUBE_SQL_PORT
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: db-port
          - name: AWS_S3_BUCKET
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: aws-s3-bucket
          - name: THIS_POD_IP
            valueFrom:
              fieldRef:
                fieldPath: status.podIP
          - name: DISCORD_CLIENTID
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: discord-client-id
          - name: DISCORD_CLIENTSECRET
            valueFrom:
              secretKeyRef:
                name: api-secrets
                key: discord-client-secret
      restartPolicy: Never
  backoffLimit: 0
