apiVersion: batch/v1
kind: CronJob
metadata:
  name: spellbook-reddit-bot-daily-update
  namespace: spellbook-reddit-bot-prod
spec:
  timeZone: America/Los_Angeles
  schedule: '30 8 * * *'
  jobTemplate:
    spec:
      template:
        spec:
          serviceAccountName: app-service-account
          containers:
            - name: updater-image
              image: 083767677168.dkr.ecr.us-east-2.amazonaws.com/spellbook-prod-reddit-ecr
              command:
                - /bin/sh
                - -c
                - python spellbook_reddit.py --daily;
              env:
                - name: KUBE_REDDIT_USERNAME
                  valueFrom:
                    secretKeyRef:
                      name: reddit-bot-secrets
                      key: reddit-username
                - name: KUBE_REDDIT_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: reddit-bot-secrets
                      key: reddit-password
                - name: KUBE_REDDIT_CLIENT_ID
                  valueFrom:
                    secretKeyRef:
                      name: reddit-bot-secrets
                      key: reddit-client-id
                - name: KUBE_REDDIT_CLIENT_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: reddit-bot-secrets
                      key: reddit-client-secret
                - name: SPELLBOOK_API_URL
                  value: https://backend.commanderspellbook.com
                - name: SPELLBOOK_WEBSITE_URL
                  value: https://commanderspellbook.com
          restartPolicy: Never
  concurrencyPolicy: Forbid
