SCRYFALL_API_ROOT = 'https://api.scryfall.com'

SCRYFALL_API_CARD_SEARCH = SCRYFALL_API_ROOT + '/cards/search'

SCRYFALL_WEBSITE_ROOT = 'https://scryfall.com'

SCRYFALL_WEBSITE_CARD_SEARCH = SCRYFALL_WEBSITE_ROOT + '/search'

SCRYFALL_LEGAL_IN_COMMANDER = 'legal:commander'
