# Generated by Django 4.0.6 on 2022-07-10 22:13

from django.db import migrations, models
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(help_text='Card name', max_length=255, unique=True, verbose_name='name of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='oracle_id',
            field=models.UUIDField(blank=True, help_text='Scryfall Oracle ID', unique=True, verbose_name='Scryfall Oracle ID of card'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='description',
            field=models.TextField(blank=True, help_text='Long description of a produced effect', verbose_name='description of feature'),
        ),
        migrations.AlterField(
            model_name='feature',
            name='name',
            field=models.CharField(help_text='Short name for a produced effect', max_length=255, unique=True, verbose_name='name of feature'),
        ),
        AlterSortedManyToManyField(
            model_name='variant',
            name='includes',
            field=sortedm2m.fields.SortedManyToManyField(editable=False, help_text='Cards that this variant includes', related_name='included_in_variants', to='spellbook.card'),
        ),
    ]
