# Generated by Django 4.1 on 2022-09-06 10:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='mana_needed',
            field=models.CharField(blank=True, default='', help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=200, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format.', regex='^(\\{(?:[0-9WUBRGCXS]|[1-9][0-9]|([2WUBRG])(?:\\/(?!\\2)[WUBRG])?(?:\\/P)?)\\} *)*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='mana_needed',
            field=models.CharField(blank=True, default='', help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=200, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format.', regex='^(\\{(?:[0-9WUBRGCXS]|[1-9][0-9]|([2WUBRG])(?:\\/(?!\\2)[WUBRG])?(?:\\/P)?)\\} *)*$')]),
        ),
    ]
