# Generated by Django 4.1.5 on 2023-03-26 13:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_alter_card_identity_alter_variant_identity'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='frozen',
        ),
    ]
