# Generated by Django 4.0.6 on 2022-07-11 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0002_alter_card_name_alter_card_oracle_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='status',
            field=models.CharField(choices=[('NW', 'Not Working'), ('D', 'Draft'), ('OK', 'Ok'), ('R', 'Restore')], default='D', help_text='Variant status for editors', max_length=2),
        ),
    ]
