# Generated by Django 5.0 on 2023-12-24 11:38

import django.core.validators
import spellbook.models.card
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0003_variant_popularity_and_django5_fields'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='name_unaccented_simplified',
        ),
        migrations.RemoveField(
            model_name='card',
            name='name_unaccented_simplified_with_spaces',
        ),
        migrations.AddField(
            model_name='card',
            name='keywords',
            field=models.JSONField(default=list, help_text='Oracle card keywords', validators=[spellbook.models.fields.validate_keyword_json], verbose_name='oracle keywords of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_value',
            field=models.PositiveSmallIntegerField(default=0, help_text='Mana value of card', verbose_name='mana value of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='reserved',
            field=models.BooleanField(default=False, help_text='Whether this card is part of the Reserved List', verbose_name='reserved list card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='identity',
            field=models.CharField(default='C', max_length=5, validators=[django.core.validators.RegexValidator(message='Can be any combination of one or more letters in [W,U,B,R,G], in order, otherwise C for colorless.', regex='^(?:W?U?B?R?G?|C)$'), django.core.validators.MinLengthValidator(1)], verbose_name='mana identity'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='identity',
            field=models.CharField(default='C', max_length=5, validators=[django.core.validators.RegexValidator(message='Can be any combination of one or more letters in [W,U,B,R,G], in order, otherwise C for colorless.', regex='^(?:W?U?B?R?G?|C)$'), django.core.validators.MinLengthValidator(1)], verbose_name='mana identity'),
        ),
    ]
