# Generated by Django 4.0.6 on 2022-07-16 00:08

from django.db import migrations
import sortedm2m.fields
from sortedm2m.operations import AlterSortedManyToManyField


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0003_alter_variant_status'),
    ]

    operations = [
        AlterSortedManyToManyField(
            model_name='variant',
            name='produces',
            field=sortedm2m.fields.SortedManyToManyField(editable=False, help_text='Features that this variant produces', related_name='produced_by_variants', to='spellbook.feature'),
        ),
    ]
