# Generated by Django 5.0 on 2023-12-24 11:39

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_update_card_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name_unaccented_simplified',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('name_unaccented'), models.Value('-'), models.Value('')), models.Value('_____'), models.Value(''))), output_field=models.CharField(editable=False, help_text='Card name without accents or hyphens', max_length=255, unique=True, verbose_name='name of card without accents or hyphens')),
        ),
        migrations.AddField(
            model_name='card',
            name='name_unaccented_simplified_with_spaces',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('name_unaccented'), models.Value('-'), models.Value(' ')), models.Value('_____'), models.Value('_'))), output_field=models.CharField(editable=False, help_text='Card name without accents or hyphens, with spaces', max_length=255, unique=True, verbose_name='name of card without accents or hyphens, with spaces')),
        ),
    ]
