# Generated by Django 4.0.6 on 2022-07-19 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_alter_variant_produces'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Draft'), ('NW', 'Not Working'), ('OK', 'Ok'), ('R', 'Restore')], default='N', help_text='Variant status for editors', max_length=2),
        ),
    ]
