# Generated by Django 4.1 on 2022-10-03 23:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0004_template_template_card_template_name_index'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='template',
            options={'ordering': ['name'], 'verbose_name': 'card template', 'verbose_name_plural': 'templates'},
        ),
        migrations.AddField(
            model_name='combo',
            name='requires',
            field=models.ManyToManyField(blank=True, help_text='Templates that this combo requires', related_name='required_by_combos', to='spellbook.template', verbose_name='required templates'),
        ),
        migrations.AddField(
            model_name='variant',
            name='requires',
            field=models.ManyToManyField(blank=True, help_text='Templates that this variant requires', related_name='required_by_variants', to='spellbook.template', verbose_name='required templates'),
        ),
    ]
