# Generated by Django 5.0 on 2023-12-30 19:44

from django.db import migrations, models


def update_line_counts(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    variants = list(Variant.objects.all())
    for variant in variants:
        variant.description_line_count = variant.description.count('\n') + 1 if variant.description else 0
        variant.other_prerequisites_line_count = variant.other_prerequisites.count('\n') + 1 if variant.other_prerequisites else 0
    Variant.objects.bulk_update(
        variants,
        ['description_line_count', 'other_prerequisites_line_count'],
        5000
    )


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0005_add_back_altered_generated_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='description_line_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of lines in the description'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='other_prerequisites_line_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of lines in the other prerequisites'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='variant',
            name='popularity',
            field=models.PositiveIntegerField(db_default=models.Value(None), editable=False, help_text='Popularity of this variant, provided by EDHREC', null=True),
        ),
        migrations.RunPython(update_line_counts, reverse_code=migrations.RunPython.noop),
    ]
