# Generated by Django 4.2.1 on 2023-07-19 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0005_alter_combo_mana_needed_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardincombo',
            name='must_be_commander',
            field=models.BooleanField(default=False, help_text='Does the card have to be a commander?', verbose_name='must be commander'),
        ),
        migrations.AddField(
            model_name='cardinvariant',
            name='must_be_commander',
            field=models.BooleanField(default=False, help_text='Does the card have to be a commander?', verbose_name='must be commander'),
        ),
        migrations.AddField(
            model_name='templateincombo',
            name='must_be_commander',
            field=models.BooleanField(default=False, help_text='Does the card have to be a commander?', verbose_name='must be commander'),
        ),
        migrations.AddField(
            model_name='templateinvariant',
            name='must_be_commander',
            field=models.BooleanField(default=False, help_text='Does the card have to be a commander?', verbose_name='must be commander'),
        ),
    ]
