# Generated by Django 4.0.6 on 2022-07-19 22:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0006_combo_generator'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='removes',
            field=models.ManyToManyField(help_text='Features that this combo removes', related_name='removed_by_combos', to='spellbook.feature', verbose_name='removed features'),
        ),
    ]
