# Generated by Django 4.0.6 on 2022-07-21 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0007_combo_removes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='removes',
            field=models.ManyToManyField(blank=True, help_text='Features that this combo removes', related_name='removed_by_combos', to='spellbook.feature', verbose_name='removed features'),
        ),
    ]
