# Generated by Django 4.2.1 on 2023-06-11 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0007_alter_feature_name_alter_template_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='combo',
            name='generator',
        ),
        migrations.AddField(
            model_name='combo',
            name='kind',
            field=models.CharField(choices=[('G', 'Generator'), ('U', 'Utility'), ('M', 'Generator With Many Cards')], default='G', help_text='Is this combo a generator for variants?', max_length=2, verbose_name='kind'),
        ),
    ]
