# Generated by Django 5.0 on 2024-01-10 14:27

import spellbook.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0007_add_variant_alias'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=spellbook.models.fields.KeywordsField(help_text='Oracle card keywords', verbose_name='oracle keywords of card'),
        ),
    ]
