# Generated by Django 4.2.1 on 2023-06-27 11:39

from django.db import migrations, models
from spellbook.models.utils import strip_accents


def set_unaccented_names(apps, schema_editor):
    Card = apps.get_model('spellbook', 'Card')
    to_save = []
    for card in Card.objects.all():
        card.name_unaccented = strip_accents(card.name)
        to_save.append(card)
    Card.objects.bulk_update(to_save, ['name_unaccented'])


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0008_remove_combo_generator_combo_kind'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='name_unaccented',
            field=models.CharField(default=None, editable=False, help_text='Card name without accents', max_length=255, unique=True, verbose_name='name of card without accents', null=True),
            preserve_default=False,
        ),
        migrations.RunPython(set_unaccented_names),
        migrations.AlterField(
            model_name='card',
            name='name_unaccented',
            field=models.CharField(editable=False, help_text='Card name without accents', max_length=255, unique=True, verbose_name='name of card without accents', null=False),
        ),
    ]
