# Generated by Django 5.0.1 on 2024-01-11 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0008_alter_card_keywords'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='serialized',
            field=models.JSONField(blank=True, editable=False, null=True),
        ),
    ]
