# Generated by Django 4.0.6 on 2022-07-25 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0008_alter_combo_removes'),
    ]

    operations = [
        migrations.CreateModel(
            name='Jobs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Job name', max_length=255, verbose_name='name of job')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('expected_duration', models.DurationField(editable=False)),
            ],
            options={
                'verbose_name': 'job',
                'verbose_name_plural': 'jobs',
                'ordering': ['-created', 'name'],
            },
        ),
        migrations.AddIndex(
            model_name='jobs',
            index=models.Index(fields=['name'], name='job_name_index'),
        ),
    ]
