# Generated by Django 4.1.5 on 2023-02-07 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0009_alter_template_scryfall_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='legal',
            field=models.BooleanField(default=True, help_text='Is this card legal in Commander?', verbose_name='is legal'),
        ),
        migrations.AddField(
            model_name='variant',
            name='legal',
            field=models.BooleanField(default=True, help_text='Is this variant legal in Commander?', verbose_name='is legal'),
        ),
    ]
