# Generated by Django 4.0.6 on 2022-07-25 15:53

import datetime
from django.db import migrations, models
import django.db.models.expressions
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0009_jobs_jobs_job_name_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jobs',
            name='expected_duration',
        ),
        migrations.AddField(
            model_name='jobs',
            name='expected_termination',
            field=models.DateTimeField(default=datetime.datetime(2022, 7, 25, 15, 53, 36, 523227, tzinfo=utc), editable=False),
            preserve_default=False,
        ),
        migrations.AddConstraint(
            model_name='jobs',
            constraint=models.CheckConstraint(check=models.Q(('expected_termination__gte', django.db.models.expressions.F('created'))), name='job_expected_termination_gte_created'),
        ),
    ]
