# Generated by Django 4.0.6 on 2022-07-25 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0010_remove_jobs_expected_duration_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='message',
            field=models.TextField(blank=True, editable=False, help_text='job message'),
        ),
        migrations.AddField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failure'), ('P', 'Pending')], default='P', editable=False, help_text='Job status', max_length=2),
        ),
        migrations.AddField(
            model_name='jobs',
            name='termination',
            field=models.DateTimeField(blank=True, editable=False, null=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(help_text='job name', max_length=255, verbose_name='name of job'),
        ),
    ]
