# Generated by Django 5.0.1 on 2024-01-15 11:06

import django.db.models.deletion
from django.db import migrations, models


def migrate_feature_needed_through(apps, schema_editor):
    FeatureNeededInCombo = apps.get_model('spellbook', 'FeatureNeededInCombo')
    Combo = apps.get_model('spellbook', 'Combo')
    to_create = []
    for combo in Combo.objects.prefetch_related('needs'):
        for feature in combo.needs.all():
            to_create.append(FeatureNeededInCombo(combo=combo, feature=feature))
    FeatureNeededInCombo.objects.bulk_create(to_create)


def reverse_migrate_feature_needed_through(apps, schema_editor):
    FeatureNeededInCombo = apps.get_model('spellbook', 'FeatureNeededInCombo')
    FeatureNeededInComboOld = apps.get_model('spellbook', 'Combo').needs.through
    to_create = []
    for feature_needed in FeatureNeededInCombo.objects.all():
        to_create.append(FeatureNeededInComboOld(combo_id=feature_needed.combo.id, feature_id=feature_needed.feature.id))
    for i, obj in enumerate(to_create):
        obj.id = i + 1
        obj.save(force_insert=True)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0010_name_field_on_recipes'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureNeededInCombo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('combo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.combo')),
                ('feature', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.feature')),
            ],
            options={
                'unique_together': {('feature', 'combo')},
            },
        ),
        migrations.RunPython(
            migrate_feature_needed_through,
            reverse_code=reverse_migrate_feature_needed_through,
        ),
        migrations.RemoveField(
            model_name='combo',
            name='needs',
        ),
        migrations.AddField(
            model_name='combo',
            name='needs',
            field=models.ManyToManyField(blank=True, help_text='Features that this combo needs', related_name='needed_by_combos', through='spellbook.FeatureNeededInCombo', to='spellbook.feature', verbose_name='needed features'),
        ),
    ]
