# Generated by Django 4.0.6 on 2022-07-25 21:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('spellbook', '0011_jobs_message_jobs_status_jobs_termination_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobs',
            name='started_by',
            field=models.ForeignKey(blank=True, help_text='User that started this job', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='started_jobs', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='expected_termination',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='message',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='name',
            field=models.CharField(max_length=255, verbose_name='name of job'),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='status',
            field=models.CharField(choices=[('S', 'Success'), ('F', 'Failure'), ('P', 'Pending')], default='P', max_length=2),
        ),
        migrations.AlterField(
            model_name='jobs',
            name='termination',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
