# Generated by Django 4.1.5 on 2023-02-10 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0011_remove_combo_cards_state_remove_combo_zone_locations_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cardincombo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='cardinvariant',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='templateincombo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterModelOptions(
            name='templateinvariant',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AlterUniqueTogether(
            name='cardincombo',
            unique_together={('card', 'combo')},
        ),
        migrations.AlterUniqueTogether(
            name='cardinvariant',
            unique_together={('card', 'variant')},
        ),
        migrations.AlterUniqueTogether(
            name='templateincombo',
            unique_together={('template', 'combo')},
        ),
        migrations.AlterUniqueTogether(
            name='templateinvariant',
            unique_together={('template', 'variant')},
        ),
    ]
