# Generated by Django 4.1.5 on 2023-02-12 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0012_alter_cardincombo_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cardincombo',
            name='zone_location',
            field=models.CharField(choices=[('H', 'Hand'), ('B', 'Battlefield'), ('C', 'Command Zone'), ('G', 'Graveyard'), ('L', 'Library'), ('E', 'Exile'), ('A', 'Any')], default='H', help_text='Starting location for the card.', max_length=2, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='cardinvariant',
            name='zone_location',
            field=models.CharField(choices=[('H', 'Hand'), ('B', 'Battlefield'), ('C', 'Command Zone'), ('G', 'Graveyard'), ('L', 'Library'), ('E', 'Exile'), ('A', 'Any')], default='H', help_text='Starting location for the card.', max_length=2, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='templateincombo',
            name='zone_location',
            field=models.CharField(choices=[('H', 'Hand'), ('B', 'Battlefield'), ('C', 'Command Zone'), ('G', 'Graveyard'), ('L', 'Library'), ('E', 'Exile'), ('A', 'Any')], default='H', help_text='Starting location for the card.', max_length=2, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='templateinvariant',
            name='zone_location',
            field=models.CharField(choices=[('H', 'Hand'), ('B', 'Battlefield'), ('C', 'Command Zone'), ('G', 'Graveyard'), ('L', 'Library'), ('E', 'Exile'), ('A', 'Any')], default='H', help_text='Starting location for the card.', max_length=2, verbose_name='starting location'),
        ),
    ]
