# Generated by Django 5.0.1 on 2024-01-20 02:06

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0013_spoiler_field_in_suggestion_and_scryfall_queries'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variantsuggestion',
            options={'ordering': [models.Case(models.When(status='NR', then=models.Value(0)), models.When(status='N', then=models.Value(1)), models.When(status='A', then=models.Value(2)), models.When(status='R', then=models.Value(3)), default=models.Value(10)), '-created'], 'verbose_name': 'variant suggestion', 'verbose_name_plural': 'variant suggestions'},
        ),
        migrations.AddField(
            model_name='variantsuggestion',
            name='comment',
            field=models.TextField(blank=True, help_text='Comment written by the user that suggested this combo', max_length=1024, validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\})*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF]*$')]),
        ),
        migrations.AlterField(
            model_name='variantsuggestion',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('NR', 'Needs Review'), ('A', 'Accepted'), ('R', 'Rejected')], default='N', help_text='Suggestion status for editors', max_length=2),
        ),
    ]
