# Generated by Django 4.0.6 on 2022-08-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0013_variant_frozen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='frozen',
            field=models.BooleanField(default=False, help_text='Is this variant undeletable?', verbose_name='is frozen'),
        ),
    ]
