# Generated by Django 5.0.1 on 2024-02-03 12:37

import django.db.models.functions.text
import spellbook.models.mixins
import spellbook.models.variant
from django.db import migrations, models


def update_variant_counts(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    v = Variant.objects.annotate(
        new_cards_count=models.Count('uses', distinct=True) + models.Count('requires', distinct=True),
        new_results_count=models.Count('produces', distinct=True),
    )
    for variant in v:
        variant.pre_save = lambda: None
        variant.cards_count = variant.new_cards_count
        variant.results_count = variant.new_results_count
    Variant.objects.bulk_update(v, ['cards_count', 'results_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0014_alter_variantsuggestion'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='card',
            managers=[
                ('objects', spellbook.models.mixins.PreSaveManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='variant',
            managers=[
                ('recipes_prefetched', spellbook.models.variant.RecipePrefetchedManager()),
                ('objects', spellbook.models.mixins.PreSaveSerializedManager()),
            ],
        ),
        migrations.AddField(
            model_name='card',
            name='identity_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(identity='C', then=models.Value(0)), default=django.db.models.functions.text.Length('identity')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='identity color count')),
        ),
        migrations.AddField(
            model_name='variant',
            name='cards_count',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(identity='C', then=models.Value(0)), default=django.db.models.functions.text.Length('identity')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='identity color count')),
        ),
        migrations.AddField(
            model_name='variant',
            name='results_count',
            field=models.PositiveIntegerField(default=0, editable=False),
            preserve_default=False,
        ),
        migrations.RunPython(update_variant_counts, migrations.RunPython.noop),
    ]
