# Generated by Django 5.0.1 on 2024-02-02 17:50

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0014_alter_variantsuggestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='cards_count',
            field=models.PositiveIntegerField(default=1, verbose_name='cards count'),
        ),
        migrations.AddField(
            model_name='card',
            name='identity_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(identity='C', then=models.Value(0)), default=django.db.models.functions.text.Length('identity')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='identity color count')),
        ),
        migrations.AddField(
            model_name='variant',
            name='cards_count',
            field=models.PositiveIntegerField(default=1, verbose_name='cards count'),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(identity='C', then=models.Value(0)), default=django.db.models.functions.text.Length('identity')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='identity color count')),
        ),
        migrations.AddField(
            model_name='variant',
            name='results_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of results for this variant'),
            preserve_default=False,
        ),
    ]
