# Generated by Django 5.0 on 2024-02-06 00:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0015_cache_variant_search_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='identity',
            field=models.CharField(choices=[('C', 'C'), ('W', 'W'), ('U', 'U'), ('B', 'B'), ('R', 'R'), ('G', 'G'), ('WU', 'WU'), ('WB', 'WB'), ('RW', 'RW'), ('GW', 'GW'), ('UB', 'UB'), ('UR', 'UR'), ('GU', 'GU'), ('BR', 'BR'), ('BG', 'BG'), ('RG', 'RG'), ('WUB', 'WUB'), ('URW', 'URW'), ('GWU', 'GWU'), ('RWB', 'RWB'), ('WBG', 'WBG'), ('RGW', 'RGW'), ('UBR', 'UBR'), ('BGU', 'BGU'), ('GUR', 'GUR'), ('BRG', 'BRG'), ('WUBR', 'WUBR'), ('UBRG', 'UBRG'), ('BRGW', 'BRGW'), ('RGWU', 'RGWU'), ('GWUB', 'GWUB'), ('WUBRG', 'WUBRG')], default='C', max_length=5, verbose_name='mana identity'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='identity',
            field=models.CharField(choices=[('C', 'C'), ('W', 'W'), ('U', 'U'), ('B', 'B'), ('R', 'R'), ('G', 'G'), ('WU', 'WU'), ('WB', 'WB'), ('RW', 'RW'), ('GW', 'GW'), ('UB', 'UB'), ('UR', 'UR'), ('GU', 'GU'), ('BR', 'BR'), ('BG', 'BG'), ('RG', 'RG'), ('WUB', 'WUB'), ('URW', 'URW'), ('GWU', 'GWU'), ('RWB', 'RWB'), ('WBG', 'WBG'), ('RGW', 'RGW'), ('UBR', 'UBR'), ('BGU', 'BGU'), ('GUR', 'GUR'), ('BRG', 'BRG'), ('WUBR', 'WUBR'), ('UBRG', 'UBRG'), ('BRGW', 'BRGW'), ('RGWU', 'RGWU'), ('GWUB', 'GWUB'), ('WUBRG', 'WUBRG')], default='C', max_length=5, verbose_name='mana identity'),
        ),
    ]
