# Generated by Django 4.0.7 on 2022-08-30 17:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0015_rename_jobs_job'),
    ]

    operations = [
        migrations.AddField(
            model_name='feature',
            name='utility',
            field=models.BooleanField(default=False, help_text='Is this a utility feature? Utility features are hidden to the end users', verbose_name='is utility feature'),
        ),
    ]
