# Generated by Django 4.1.5 on 2023-03-16 19:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0016_card_spoiler_variant_spoiler_alter_variant_legal'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
