# Generated by Django 4.0.7 on 2022-09-02 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0016_feature_utility'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='utility',
            field=models.BooleanField(default=False, help_text='Is this a utility feature? Utility features are hidden to the end users', verbose_name='is utility'),
        ),
    ]
