# Generated by Django 4.1.5 on 2023-03-15 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0016_card_spoiler'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='legal',
        ),
    ]
