# Generated by Django 4.0.7 on 2022-09-03 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0017_alter_feature_utility'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='variants',
            field=models.ManyToManyField(blank=True, editable=False, help_text='Variants that this job added or updated', related_name='jobs', to='spellbook.variant', verbose_name='variants updated'),
        ),
    ]
