# Generated by Django 4.1 on 2022-09-05 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0018_job_variants'),
    ]

    operations = [
        migrations.RenameField(
            model_name='combo',
            old_name='prerequisites',
            new_name='other_prerequisites',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='prerequisites',
            new_name='other_prerequisites',
        ),
        migrations.AddField(
            model_name='combo',
            name='cards_state',
            field=models.TextField(blank=True, help_text='State of cards in their starting locations.'),
        ),
        migrations.AddField(
            model_name='combo',
            name='mana_needed',
            field=models.CharField(blank=True, help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G} format.', max_length=50, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G} format.', regex='^(?:\\{(?:[0-9WUBRGCXS]|1[0-6])(?:\\/[WUBRG])?(?:\\/[WUBRGP])?\\})*$')]),
        ),
        migrations.AddField(
            model_name='combo',
            name='zone_locations',
            field=models.TextField(blank=True, help_text='Starting locations for cards.'),
        ),
        migrations.AddField(
            model_name='variant',
            name='cards_state',
            field=models.TextField(blank=True, help_text='State of cards in their starting locations.'),
        ),
        migrations.AddField(
            model_name='variant',
            name='mana_needed',
            field=models.TextField(blank=True, help_text='Mana needed for this variant.'),
        ),
        migrations.AddField(
            model_name='variant',
            name='zone_locations',
            field=models.TextField(blank=True, help_text='Starting locations for cards.'),
        )
    ]
