# Generated by Django 4.1 on 2022-09-05 15:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0019_remove_combo_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='other_prerequisites',
            field=models.TextField(blank=True, help_text='Other prerequisites for this combo.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='other_prerequisites',
            field=models.TextField(blank=True, help_text='Other prerequisites for this variant.'),
        ),
    ]
