# Generated by Django 5.0.4 on 2024-04-23 06:41

import django.db.models.functions.text
from django.db import migrations, models
import spellbook.models.mixins
from spellbook.models.utils import strip_accents


def migrate_suggested_card_unaccented_names(apps, schema_editor):
    CardUsedInVariantSuggestion = apps.get_model('spellbook', 'CardUsedInVariantSuggestion')
    suggestions = list(CardUsedInVariantSuggestion.objects.all())
    for suggestion in suggestions:
        suggestion.card_unaccented = strip_accents(suggestion.card)
        suggestion.pre_save = lambda: None
    CardUsedInVariantSuggestion.objects.bulk_update(suggestions, ['card_unaccented'])


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0019_cumulative_updates'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardusedinvariantsuggestion',
            name='card_unaccented',
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
        migrations.AddField(
            model_name='cardusedinvariantsuggestion',
            name='card_unaccented_simplified',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('card_unaccented'), models.Value('-'), models.Value('')), models.Value('_____'), models.Value(''))), output_field=models.CharField(blank=True, editable=False, max_length=255)),
        ),
        migrations.AddField(
            model_name='cardusedinvariantsuggestion',
            name='card_unaccented_simplified_with_spaces',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('card_unaccented'), models.Value('-'), models.Value(' ')), models.Value('_____'), models.Value('_'))), output_field=models.CharField(blank=True, editable=False, max_length=255)),
        ),
        migrations.AlterModelManagers(
            name='cardusedinvariantsuggestion',
            managers=[
                ('objects', spellbook.models.mixins.PreSaveManager()),
            ],
        ),
        migrations.RunPython(
            code=migrate_suggested_card_unaccented_names,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
