# Generated by Django 4.1 on 2022-09-05 16:11

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0020_alter_combo_other_prerequisites_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='cards_state',
            field=models.TextField(blank=True, default='', help_text='State of cards in their starting locations.'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='mana_needed',
            field=models.CharField(blank=True, default='', help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G} format.', max_length=50, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G} format.', regex='^(?:\\{(?:[0-9WUBRGCXS]|1[0-6])(?:\\/[WUBRG])?(?:\\/[WUBRGP])?\\})*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='other_prerequisites',
            field=models.TextField(blank=True, default='', help_text='Other prerequisites for this combo.'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='zone_locations',
            field=models.TextField(blank=True, default='', help_text='Starting locations for cards.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='cards_state',
            field=models.TextField(blank=True, default='', help_text='State of cards in their starting locations.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='mana_needed',
            field=models.TextField(blank=True, default='', help_text='Mana needed for this variant.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='other_prerequisites',
            field=models.TextField(blank=True, default='', help_text='Other prerequisites for this variant.'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='zone_locations',
            field=models.TextField(blank=True, default='', help_text='Starting locations for cards.'),
        ),
    ]
