# Generated by Django 5.0.6 on 2024-06-12 21:44

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations
try:
    from django.contrib.postgres.operations import TrigramExtension
    extra_operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='card_gin_trgm_name'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name_unaccented'), name='gin_trgm_ops'), name='card_gin_trgm_name_unacc'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name_unaccented_simplified'), name='gin_trgm_ops'), name='card_gin_trgm_name_unacc_s'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name_unaccented_simplified_with_spaces'), name='gin_trgm_ops'), name='card_gin_trgm_name_unacc_sws'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('oracle_text'), name='gin_trgm_ops'), name='card_gin_trgm_oracle_text'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('type_line'), name='gin_trgm_ops'), name='card_gin_trgm_type_line'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('keywords'), name='gin_trgm_ops'), name='card_gin_trgm_keywords'),
        ),
        migrations.AddIndex(
            model_name='feature',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='feature_gin_trgm_name'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('other_prerequisites'), name='gin_trgm_ops'), name='variant_gin_trgm_other_prereq'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='variant_gin_trgm_description'),
        ),
    ]
except ImportError:
    extra_operations = []


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0022_alter_cardincombo_order_alter_cardinvariant_order_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_name_037e1e_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_type_li_155b2b_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_oracle__78c83a_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_keyword_c42092_gin',
        ),
        migrations.RemoveIndex(
            model_name='feature',
            name='spellbook_f_name_fedfaa_gin',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_other_p_4121cc_gin',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_descrip_26b373_gin',
        ),
        *extra_operations,
    ]
