# Generated by Django 4.1 on 2022-09-05 16:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0022_alter_variant_mana_needed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='mana_needed',
            field=models.CharField(blank=True, default='', help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=50, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format.', regex='^(?:\\{(?:[0-9WUBRGCXS]|1[0-6])(?:\\/[WUBRG])?(?:\\/[WUBRGP])?\\})*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='mana_needed',
            field=models.CharField(blank=True, default='', help_text='Mana needed for this combo. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=50, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format.', regex='^(?:\\{(?:[0-9WUBRGCXS]|1[0-6])(?:\\/[WUBRG])?(?:\\/[WUBRGP])?\\})*$')]),
        ),
    ]
