# Generated by Django 5.0.6 on 2024-06-16 19:59

import django.contrib.postgres.indexes
import django.db.models.functions.text
from django.db import migrations, connection

if connection.vendor == 'postgresql':
    from django.contrib.postgres.operations import TrigramExtension
    extra_operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_name_037e1e_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_type_li_155b2b_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_oracle__78c83a_gin',
        ),
        migrations.RemoveIndex(
            model_name='card',
            name='spellbook_c_keyword_c42092_gin',
        ),
        migrations.RemoveIndex(
            model_name='feature',
            name='spellbook_f_name_fedfaa_gin',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_other_p_4121cc_gin',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_descrip_26b373_gin',
        ),
        TrigramExtension(),
        migrations.RunSQL(
            sql='CREATE INDEX "card_name_trgm_idx" ON "spellbook_card" USING gin (UPPER("name") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_name_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "card_name_unacc_trgm_idx" ON "spellbook_card" USING gin (UPPER("name_unaccented") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_name_unacc_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "card_name_unac_sim_trgm_idx" ON "spellbook_card" USING gin (UPPER("name_unaccented_simplified") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_name_unac_sim_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "card_name_unac_sim_sp_trgm_idx" ON "spellbook_card" USING gin (UPPER("name_unaccented_simplified_with_spaces") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_name_unac_sim_sp_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "card_type_line_trgm_idx" ON "spellbook_card" USING gin (UPPER("type_line") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_type_line_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "card_oracle_text_trgm_idx" ON "spellbook_card" USING gin (UPPER("oracle_text") gin_trgm_ops)',
            reverse_sql='DROP INDEX "card_oracle_text_trgm_idx"'
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(fields=['keywords'], name='card_keywords_trgm_idx'),
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "feature_name_trgm_idx" ON "spellbook_feature" USING gin (UPPER("name") gin_trgm_ops)',
            reverse_sql='DROP INDEX "feature_name_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "variant_other_prereq_trgm_idx" ON "spellbook_variant" USING gin (UPPER("other_prerequisites") gin_trgm_ops)',
            reverse_sql='DROP INDEX "variant_other_prereq_trgm_idx"'
        ),
        migrations.RunSQL(
            sql='CREATE INDEX "variant_description_trgm_idx" ON "spellbook_variant" USING gin (UPPER("description") gin_trgm_ops)',
            reverse_sql='DROP INDEX "variant_description_trgm_idx"'
        ),
    ]
else:
    extra_operations = []


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0022_alter_cardincombo_order_alter_cardinvariant_order_and_more'),
    ]

    operations = [
        *extra_operations,
    ]
