# Generated by Django 5.0.6 on 2024-06-18 18:20

from django.db import migrations, models
import django.db.models.functions.text
import spellbook.models.fields
import spellbook.models.ingredient
from ._utils import PopulateNameField


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0023_use_trigram_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        migrations.AlterField(
            model_name='variantsuggestion',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        PopulateNameField(),
        migrations.AlterField(
            model_name='card',
            name='keywords',
            field=spellbook.models.fields.KeywordsField(default=list, verbose_name='oracle keywords of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='mana_value',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='mana value of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='name of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_unaccented',
            field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='name of card without accents'),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_unaccented_simplified',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('name_unaccented'), models.Value('-'), models.Value('')), models.Value('_____'), models.Value(''))), output_field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='name of card without accents or hyphens')),
        ),
        migrations.AlterField(
            model_name='card',
            name='name_unaccented_simplified_with_spaces',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Trim(django.db.models.functions.text.Replace(django.db.models.functions.text.Replace(models.F('name_unaccented'), models.Value('-'), models.Value(' ')), models.Value('_____'), models.Value('_'))), output_field=models.CharField(editable=False, max_length=255, unique=True, verbose_name='name of card without accents or hyphens, with spaces')),
        ),
        migrations.AlterField(
            model_name='card',
            name='oracle_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='Scryfall Oracle ID of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='oracle_text',
            field=models.TextField(blank=True, verbose_name='oracle text of card'),
        ),
        migrations.AlterField(
            model_name='card',
            name='type_line',
            field=models.CharField(blank=True, max_length=255, verbose_name='type line of card'),
        ),
        migrations.AlterField(
            model_name='cardincombo',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='cardinvariant',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='cardusedinvariantsuggestion',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='allow_multiple_copies',
            field=models.BooleanField(default=False, help_text='Allow variants to have more copies of the same card or template'),
        ),
        migrations.AlterField(
            model_name='featureofcard',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='templateincombo',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='templateinvariant',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
        migrations.AlterField(
            model_name='templaterequiredinvariantsuggestion',
            name='zone_locations',
            field=spellbook.models.ingredient.ZoneLocationsField(default='H', help_text='Starting location(s) for the card.', max_length=6, verbose_name='starting location'),
        ),
    ]
