# Generated by Django 5.0.6 on 2024-06-18 18:20

from django.db import migrations, models
from ._utils import PopulateNameField


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0023_use_trigram_indexes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        migrations.AlterField(
            model_name='variantsuggestion',
            name='name',
            field=models.CharField(editable=False, max_length=3925),
        ),
        PopulateNameField(),
    ]
