# Generated by Django 5.0.6 on 2024-06-24 07:23

import spellbook.models.ingredient
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0024_update_recipe_name_generator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureneededincombo',
            name='zone_locations_override',
            field=spellbook.models.ingredient.ZoneLocationsField(blank=True, default='', help_text='Option to override the zone locations for the card(s) this feature replaces.', max_length=6, verbose_name='zone locations override'),
        ),
    ]
