# Generated by Django 5.0.6 on 2024-06-29 17:05

import django.core.validators
import spellbook.models.variant_alias
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0025_featureneededincombo_zone_locations_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureofcard',
            name='other_prerequisites',
            field=models.TextField(blank=True, help_text='Other prerequisites that enable the feature for this card.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\})*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.CharField(help_text='Unique ID for this variant', max_length=128, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='variantalias',
            name='id',
            field=models.CharField(help_text='Unique id of this variant alias', max_length=128, primary_key=True, serialize=False, validators=[spellbook.models.variant_alias.no_variant_with_this_id], verbose_name='ID'),
        ),
    ]
