# Generated by Django 5.0.6 on 2024-07-17 10:29

from django.db import migrations, models
from spellbook.models import Variant as VariantModel


def initial_published(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    Variant.objects.update(published=models.Q(status__in=VariantModel.public_statuses()))


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0027_alter_cardincombo_zone_locations_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='published',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant has been published'),
        ),
        migrations.RunPython(
            code=initial_published,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
