# Generated by Django 5.0.7 on 2024-07-23 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0028_variant_published_and_scryfall_grammar_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='args',
            field=models.JSONField(blank=True, default=list, verbose_name='arguments for job'),
        ),
        migrations.AddField(
            model_name='job',
            name='group',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='group of job'),
        ),
    ]
