# Generated by Django 5.1.1 on 2024-10-03 09:15

from django.db import migrations, models


def init_variant_count(apps, schema_editor):
    Card = apps.get_model('spellbook', 'Card')
    Variant = apps.get_model('spellbook', 'Variant')
    Card.objects.update(
        variant_count=models.functions.Coalesce(
            models.Subquery(
                Variant
                .objects
                .filter(uses=models.OuterRef('pk'), status__in=('OK', 'E'))
                .values('uses')
                .annotate(total=models.Count('pk'))
                .values('total'),
            ),
            0,
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0032_alter_variant_options_alter_feature_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='variant',
            old_name='cards_count',
            new_name='card_count',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='results_count',
            new_name='result_count',
        ),
        migrations.AddField(
            model_name='card',
            name='variant_count',
            field=models.PositiveIntegerField(default=0, verbose_name='number of variants of card'),
        ),
        migrations.RunPython(init_variant_count, reverse_code=migrations.RunPython.noop),
    ]
