# Generated by Django 5.1.1 on 2024-10-18 23:17

from django.db import migrations, models


def init_variant_counts(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    variants = list(Variant.objects.only('id').annotate(
        variant_count_updated=models.Count('of__variants', distinct=True, filter=models.Q(of__variants__status__in=('OK', 'E')))
    ))
    for variant in variants:
        variant.variant_count = variant.variant_count_updated
        variant.pre_save = lambda: None
    Variant.objects.bulk_update(variants, ['variant_count'])


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0034_combo_card_count_combo_ingredient_count_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='variant_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of variants generated by the same generator combos'),
        ),
        migrations.RunPython(init_variant_counts, reverse_code=migrations.RunPython.noop),
    ]
