# Generated by Django 5.1.1 on 2024-11-04 10:02

from django.db import migrations, models


def transfer_status(apps, schema_editor):
    VariantSuggestion = apps.get_model('spellbook', 'VariantSuggestion')
    VariantSuggestion.objects.filter(status='NR').update(status='AD')
    VariantSuggestion.objects.filter(status='RE').update(status='PA')


def reverse_transfer_status(apps, schema_editor):
    VariantSuggestion = apps.get_model('spellbook', 'VariantSuggestion')
    VariantSuggestion.objects.filter(status='AD').update(status='NR')
    VariantSuggestion.objects.filter(status='PA').update(status='RE')


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0035_variant_variant_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variantsuggestion',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('AD', 'Awaiting Discussion'), ('PA', 'Pending Approval'), ('A', 'Accepted'), ('R', 'Rejected')], default='N', help_text='Suggestion status for editors', max_length=2),
        ),
        migrations.RunPython(code=transfer_status, reverse_code=reverse_transfer_status),
    ]
