# Generated by Django 5.1.1 on 2024-11-06 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0036_alter_variantsuggestion_status'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='featureneededincombo',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='featureofcard',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='featureproducedincombo',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='card',
            name='legal_premodern',
            field=models.BooleanField(default=True, help_text='Is this legal in PreModern?', verbose_name='is legal in PreModern'),
        ),
        migrations.AddField(
            model_name='variant',
            name='legal_premodern',
            field=models.BooleanField(default=True, help_text='Is this legal in PreModern?', verbose_name='is legal in PreModern'),
        ),
    ]
