# Generated by Django 5.1.1 on 2025-02-14 14:26

import django.contrib.postgres.indexes
import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models, connection

if connection.vendor == 'postgresql':
    from django.contrib.postgres.operations import TrigramExtension
    extra_operations = [
        TrigramExtension(),
        migrations.AddIndex(
            model_name='template',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('name'), name='gin_trgm_ops'), name='template_name_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), name='variant_view_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('identity_count'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), name='variant_ic_view_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('variant_count'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), name='variant_vc_view_ordering_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('card_count'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), name='variant_cc_view_ordering_idx'),
        ),
    ]
else:
    extra_operations = []


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0039_refactor_variant_suggestions'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='template',
            name='card_template_name_index',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_popular_50a711_idx',
        ),
        migrations.AddField(
            model_name='card',
            name='identity_b',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('B')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity black')),
        ),
        migrations.AddField(
            model_name='card',
            name='identity_g',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('G')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity green')),
        ),
        migrations.AddField(
            model_name='card',
            name='identity_r',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('R')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity red')),
        ),
        migrations.AddField(
            model_name='card',
            name='identity_u',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('U')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity blue')),
        ),
        migrations.AddField(
            model_name='card',
            name='identity_w',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('W')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity white')),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_b',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('B')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity black')),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_g',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('G')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity green')),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_r',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('R')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity red')),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_u',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('U')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity blue')),
        ),
        migrations.AddField(
            model_name='variant',
            name='identity_w',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('identity', models.Value('W')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='identity white')),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['status'], name='spellbook_v_status_8b8c2e_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['other_prerequisites_line_count'], name='spellbook_v_other_p_28f14d_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['description_line_count'], name='spellbook_v_descrip_8efc04_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity'], name='spellbook_v_identit_4f1cc9_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['spoiler'], name='spellbook_v_spoiler_edef79_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['mana_value'], name='spellbook_v_mana_va_59af70_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_brawl'], name='spellbook_v_legal_b_514b08_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_commander'], name='spellbook_v_legal_c_ddc9a2_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_legacy'], name='spellbook_v_legal_l_d430ec_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_modern'], name='spellbook_v_legal_m_1a9579_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_oathbreaker'], name='spellbook_v_legal_o_b2a940_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_pauper'], name='spellbook_v_legal_p_337707_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_pauper_commander'], name='spellbook_v_legal_p_13ffb6_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_pauper_commander_main'], name='spellbook_v_legal_p_0e5738_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_pioneer'], name='spellbook_v_legal_p_98cf13_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_predh'], name='spellbook_v_legal_p_d26723_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_premodern'], name='spellbook_v_legal_p_db6e3f_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_standard'], name='spellbook_v_legal_s_d98dd9_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['legal_vintage'], name='spellbook_v_legal_v_5749a0_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['price_cardkingdom'], name='spellbook_v_price_c_732b0f_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['price_cardmarket'], name='spellbook_v_price_c_3c296c_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['price_tcgplayer'], name='spellbook_v_price_t_60a974_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity_w'], name='spellbook_v_identit_39f321_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity_u'], name='spellbook_v_identit_40e4ef_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity_b'], name='spellbook_v_identit_c1138c_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity_r'], name='spellbook_v_identit_f101c7_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['identity_g'], name='spellbook_v_identit_cc3c09_idx'),
        ),
    ]
