# Generated by Django 5.1.1 on 2025-02-25 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0041_bracket_system'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='mass_land_destruction',
            new_name='mass_land_denial',
        ),
        migrations.AlterField(
            model_name='card',
            name='mass_land_denial',
            field=models.BooleanField(default=False, help_text='Whether this card can destroy multiple lands', verbose_name='mass land denial card'),
        ),
        migrations.AddField(
            model_name='variant',
            name='bracket_tag',
            field=models.CharField(choices=[('R', 'Ruthless'), ('S', 'Spicy'), ('P', 'Powerful'), ('O', 'Oddball'), ('PA', 'Precon Appropriate'), ('C', 'Casual')], default='R', editable=False, help_text='Bracket tag for this variant', max_length=2),
        ),
        migrations.AddField(
            model_name='variant',
            name='bracket_tag_override',
            field=models.CharField(blank=True, choices=[('R', 'Ruthless'), ('S', 'Spicy'), ('P', 'Powerful'), ('O', 'Oddball'), ('PA', 'Precon Appropriate'), ('C', 'Casual')], help_text='Override bracket tag for this variant', max_length=2, null=True),
        ),
        migrations.RemoveField(
            model_name='variant',
            name='bracket',
        ),
        migrations.AddField(
            model_name='variant',
            name='bracket',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(bracket_tag_override='R', then=models.Value(4)), models.When(bracket_tag_override='S', then=models.Value(3)), models.When(bracket_tag_override='P', then=models.Value(3)), models.When(bracket_tag_override='O', then=models.Value(2)), models.When(bracket_tag_override='PA', then=models.Value(2)), models.When(bracket_tag_override='C', then=models.Value(1)), models.When(bracket_tag='R', then=models.Value(4)), models.When(bracket_tag='S', then=models.Value(3)), models.When(bracket_tag='P', then=models.Value(3)), models.When(bracket_tag='O', then=models.Value(2)), models.When(bracket_tag='PA', then=models.Value(2)), models.When(bracket_tag='C', then=models.Value(1)), default=models.Value(0)), output_field=models.PositiveSmallIntegerField(help_text='Bracket number based on the tag')),
        ),
    ]
