# Generated by Django 5.1.1 on 2025-04-01 16:33

from django.db import migrations, models


def initialize_template_count(apps, schema_editor):
    Combo = apps.get_model('spellbook', 'Combo')
    Combo.objects.update(
        template_count=models.Subquery(
            Combo.objects.filter(pk=models.OuterRef('pk')).annotate(
                _template_count=models.functions.Coalesce(models.Sum('templateincombo__quantity'), 0),
            ).values('_template_count'),
        ),
    )
    Variant = apps.get_model('spellbook', 'Variant')
    Variant.objects.update(
        template_count=models.Subquery(
            Variant.objects.filter(pk=models.OuterRef('pk')).annotate(
                _template_count=models.functions.Coalesce(models.Sum('templateinvariant__quantity'), 0),
            ).values('_template_count'),
        ),
    )
    VariantSuggestion = apps.get_model('spellbook', 'VariantSuggestion')
    VariantSuggestion.objects.update(
        template_count=models.Subquery(
            VariantSuggestion.objects.filter(pk=models.OuterRef('pk')).annotate(
                _template_count=models.functions.Coalesce(models.Sum('requires__quantity'), 0),
            ).values('_template_count'),
        ),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0042_bracket_system_v2'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='template_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='variant',
            name='template_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.AddField(
            model_name='variantsuggestion',
            name='template_count',
            field=models.PositiveIntegerField(default=0, editable=False),
        ),
        migrations.RunPython(initialize_template_count, migrations.RunPython.noop),
    ]
