# Generated by Django 5.1.1 on 2025-05-27 22:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0046_remove_combo_public_notes_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variantsuggestion',
            name='variant_of',
            field=models.ForeignKey(blank=True, help_text='If this suggestion is a variant of an existing one, link it here.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggested_variants', to='spellbook.variant'),
        ),
        migrations.AlterField(
            model_name='variantupdatesuggestion',
            name='kind',
            field=models.CharField(choices=[('NW', 'Not Working'), ('SE', 'Spelling Error'), ('II', 'Incorrect Info'), ('WC', 'Wrong Card'), ('VG', 'Variant Grouping'), ('O', 'Other')], help_text='Type of suggestion', max_length=2),
        ),
    ]
