# Generated by Django 5.1.1 on 2025-07-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0048_overridable_locatons_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='combo',
            name='status',
            field=models.CharField(choices=[('G', 'Generator'), ('U', 'Utility'), ('D', 'Draft'), ('NR', 'Needs Review')], default='D', help_text='Is this combo a generator for variants?', max_length=2, verbose_name='status'),
        ),
    ]
