# Generated by Django 5.1.1 on 2025-08-06 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0048_overridable_locatons_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_uri_back_large',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the back of the card in large format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_back_normal',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the back of the card in normal format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_back_png',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the back of the card in PNG format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_back_small',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the back of the card in small format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_front_large',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the front of the card in large format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_front_normal',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the front of the card in normal format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_front_png',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the front of the card in PNG format'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_front_small',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the front of the card in small format'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='status',
            field=models.CharField(choices=[('G', 'Generator'), ('U', 'Utility'), ('D', 'Draft'), ('NR', 'Needs Review')], default='D', help_text='Is this combo a generator for variants?', max_length=2, verbose_name='status'),
        ),
    ]
