# Generated by Django 5.1.1 on 2025-08-07 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0049_card_images_and_combo_default_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='image_uri_back_art_crop',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the back of the card art crop'),
        ),
        migrations.AddField(
            model_name='card',
            name='image_uri_front_art_crop',
            field=models.URLField(blank=True, null=True, verbose_name='image URI of the card art crop'),
        ),
    ]
