# Generated by Django 5.2.6 on 2025-09-17 10:21

from django.db import migrations, models


def utility_to_public_utility(apps, schema_editor):
    Feature = apps.get_model('spellbook', 'Feature')
    Feature.objects.filter(status='U').update(status='HU')


def any_utility_to_utility(apps, schema_editor):
    Feature = apps.get_model('spellbook', 'Feature')
    Feature.objects.filter(status__in=['HU', 'PU']).update(status='U')


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0051_featureofcard_mana_needed_alter_combo_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feature',
            name='status',
            field=models.CharField(choices=[('HU', 'Hidden Utility'), ('PU', 'Public Utility'), ('H', 'Helper'), ('C', 'Contextual'), ('S', 'Standalone')], default='HU', help_text='Is this feature an utility for variant generation, a helper to be exploited somehow, or a standalone, probably impactful effect? (public utilities are visible to combo submitters)', max_length=2, verbose_name='status'),
        ),
        migrations.RunPython(
            code=utility_to_public_utility,
            reverse_code=any_utility_to_utility,
        ),
    ]
