# Generated by Django 5.2.6 on 2025-12-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0052_alter_feature_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'default_manager_name': 'objects', 'ordering': [models.Case(models.When(status='N', then=models.Value(0)), models.When(status='D', then=models.Value(1)), models.When(status='OK', then=models.Value(2)), models.When(status='E', then=models.Value(3)), models.When(status='R', then=models.Value(4)), models.When(status='NW', then=models.Value(5)), default=models.Value(10)), '-created', 'id'], 'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.AddField(
            model_name='job',
            name='version',
            field=models.CharField(default='0.1.0', max_length=50, verbose_name='application version at job start'),
            preserve_default=False,
        ),
    ]
