# Generated by Django 5.2.6 on 2025-12-24 02:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0053_alter_variant_options_job_version'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cardusedinvariantsuggestion',
            old_name='variant',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='featureproducedinvariantsuggestion',
            old_name='variant',
            new_name='suggestion',
        ),
        migrations.RenameField(
            model_name='templaterequiredinvariantsuggestion',
            old_name='variant',
            new_name='suggestion',
        ),
    ]
