# Generated by Django 5.2.9 on 2026-01-12 16:10

import django.db.models.functions.text
import django.db.models.lookups
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0054_rename_variant_cardusedinvariantsuggestion_suggestion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(choices=[('C', 'C'), ('W', 'W'), ('U', 'U'), ('B', 'B'), ('R', 'R'), ('G', 'G'), ('WU', 'WU'), ('WB', 'WB'), ('RW', 'RW'), ('GW', 'GW'), ('UB', 'UB'), ('UR', 'UR'), ('GU', 'GU'), ('BR', 'BR'), ('BG', 'BG'), ('RG', 'RG'), ('WUB', 'WUB'), ('URW', 'URW'), ('GWU', 'GWU'), ('RWB', 'RWB'), ('WBG', 'WBG'), ('RGW', 'RGW'), ('UBR', 'UBR'), ('BGU', 'BGU'), ('GUR', 'GUR'), ('BRG', 'BRG'), ('WUBR', 'WUBR'), ('UBRG', 'UBRG'), ('BRGW', 'BRGW'), ('RGWU', 'RGWU'), ('GWUB', 'GWUB'), ('WUBRG', 'WUBRG')], default='C', max_length=5, verbose_name='colors'),
        ),
        migrations.AddField(
            model_name='variant',
            name='color',
            field=models.CharField(choices=[('C', 'C'), ('W', 'W'), ('U', 'U'), ('B', 'B'), ('R', 'R'), ('G', 'G'), ('WU', 'WU'), ('WB', 'WB'), ('RW', 'RW'), ('GW', 'GW'), ('UB', 'UB'), ('UR', 'UR'), ('GU', 'GU'), ('BR', 'BR'), ('BG', 'BG'), ('RG', 'RG'), ('WUB', 'WUB'), ('URW', 'URW'), ('GWU', 'GWU'), ('RWB', 'RWB'), ('WBG', 'WBG'), ('RGW', 'RGW'), ('UBR', 'UBR'), ('BGU', 'BGU'), ('GUR', 'GUR'), ('BRG', 'BRG'), ('WUBR', 'WUBR'), ('UBRG', 'UBRG'), ('BRGW', 'BRGW'), ('RGWU', 'RGWU'), ('GWUB', 'GWUB'), ('WUBRG', 'WUBRG')], default='C', max_length=5, verbose_name='colors'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['color'], name='spellbook_v_color_48d20a_idx'),
        ),
        migrations.AddField(
            model_name='card',
            name='color_b',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('B')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color black')),
        ),
        migrations.AddField(
            model_name='card',
            name='color_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(color='C', then=models.Value(0)), default=django.db.models.functions.text.Length('color')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='color count')),
        ),
        migrations.AddField(
            model_name='card',
            name='color_g',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('G')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color green')),
        ),
        migrations.AddField(
            model_name='card',
            name='color_r',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('R')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color red')),
        ),
        migrations.AddField(
            model_name='card',
            name='color_u',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('U')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color blue')),
        ),
        migrations.AddField(
            model_name='card',
            name='color_w',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('W')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color white')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_b',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('B')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color black')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_count',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(color='C', then=models.Value(0)), default=django.db.models.functions.text.Length('color')), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='color count')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_g',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('G')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color green')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_r',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('R')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color red')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_u',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('U')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color blue')),
        ),
        migrations.AddField(
            model_name='variant',
            name='color_w',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.lookups.GreaterThan(django.db.models.functions.text.StrIndex('color', models.Value('W')), models.Value(0)), output_field=models.BooleanField(default=False, verbose_name='color white')),
        ),
    ]
