# Generated by Django 6.0.1 on 2026-01-15 18:01

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0055_add_color_to_playable'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cardinvariant',
            index=models.Index(fields=['variant_id'], include=('id', 'card_id', 'quantity'), name='cardinvariant_variant_idx'),
        ),
        migrations.AddIndex(
            model_name='templateinvariant',
            index=models.Index(fields=['variant_id'], include=('id', 'template_id', 'quantity'), name='templateinvariant_variant_idx'),
        ),
    ] if connection.vendor == 'postgresql' else []
