# Generated by Django 6.0.1 on 2026-01-22 11:14

from django.db import migrations, models


def set_is_mana_needed_total_first_turn(apps, schema_editor):
    Combo = apps.get_model('spellbook', 'Combo')
    Variant = apps.get_model('spellbook', 'Variant')

    Combo.objects.filter(mana_needed='').update(is_mana_needed_total_first_turn=True)
    Variant.objects.filter(mana_needed='').update(is_mana_needed_total_first_turn=True)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0056_cardinvariant_idx_and_templateinvariant_idx'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='is_mana_needed_total_first_turn',
            field=models.BooleanField(default=False, help_text='Does the initial {N} accurately represent the MINIMUM total mana needed on the first turn?'),
        ),
        migrations.AddField(
            model_name='variant',
            name='is_mana_needed_total_first_turn',
            field=models.BooleanField(default=False, help_text='Does the initial {N} accurately represent the MINIMUM total mana needed on the first turn?'),
        ),
        migrations.RunPython(
            code=set_is_mana_needed_total_first_turn,
            reverse_code=migrations.RunPython.noop,
        )
    ]
