# Generated by Django 6.0.1 on 2026-01-26 16:36

from django.db import migrations, models


def replace_generated_by_field(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    Variant.objects.update(generated_by=models.functions.Concat(models.Value('job_'), models.F('generated_by')))


def reverse_replace_generated_by_field(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    Variant.objects.update(generated_by=models.functions.Substr('generated_by', 5))


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0057_combo_is_mana_needed_accurate_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='job',
            name='job_name_index',
        ),
        migrations.RemoveConstraint(
            model_name='job',
            name='job_expected_termination_gte_created',
        ),
        migrations.AlterField(
            model_name='variant',
            name='generated_by',
            field=models.CharField(blank=True, editable=False, help_text='Task that generated this variant', max_length=255, null=True),
        ),
        migrations.DeleteModel(
            name='Job',
        ),
        migrations.RunPython(
            code=replace_generated_by_field,
            reverse_code=reverse_replace_generated_by_field,
        )
    ]
