# Generated by Django 6.0.1 on 2026-01-27 21:06

from django.db import migrations, models


def rename_bracket_tags(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    tag_mapping = {
        'C': 'E',  # Core -> Exhibition
        'PA': 'C',  # Precon Appropriate -> Core
    }
    for old_tag, new_tag in tag_mapping.items():
        Variant.objects.filter(bracket_tag=old_tag).update(bracket_tag=new_tag)
        Variant.objects.filter(bracket_tag_override=old_tag).update(bracket_tag_override=new_tag)


def reverse_rename_bracket_tags(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    tag_mapping = {
        'C': 'PA',  # Core <- Precon Appropriate
        'E': 'C',  # Exhibition <- Core
    }
    for new_tag, old_tag in tag_mapping.items():
        Variant.objects.filter(bracket_tag=new_tag).update(bracket_tag=old_tag)
        Variant.objects.filter(bracket_tag_override=new_tag).update(bracket_tag_override=old_tag)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0058_refactor_jobs_into_tasks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='bracket',
        ),
        migrations.RenameField(
            model_name='variant',
            old_name='is_mana_needed_total_first_turn',
            new_name='is_mana_needed_an_accurate_minimum',
        ),
        migrations.RenameField(
            model_name='combo',
            old_name='is_mana_needed_total_first_turn',
            new_name='is_mana_needed_an_accurate_minimum',
        ),
        migrations.AlterField(
            model_name='combo',
            name='is_mana_needed_an_accurate_minimum',
            field=models.BooleanField(default=False, help_text='Does the first mana cost in this field represent the MINIMUM needed to start the combo, ignoring all other text?'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_mana_needed_an_accurate_minimum',
            field=models.BooleanField(default=False, help_text='Does the first mana cost in this field represent the MINIMUM needed to start the combo, ignoring all other text?'),
        ),
        migrations.AddField(
            model_name='variant',
            name='bracket',
            field=models.GeneratedField(db_persist=True, expression=models.Case(models.When(bracket_tag_override='R', then=models.Value(4)), models.When(bracket_tag_override='S', then=models.Value(3)), models.When(bracket_tag_override='P', then=models.Value(3)), models.When(bracket_tag_override='O', then=models.Value(2)), models.When(bracket_tag_override='C', then=models.Value(2)), models.When(bracket_tag_override='E', then=models.Value(1)), models.When(bracket_tag='R', then=models.Value(4)), models.When(bracket_tag='S', then=models.Value(3)), models.When(bracket_tag='P', then=models.Value(3)), models.When(bracket_tag='O', then=models.Value(2)), models.When(bracket_tag='C', then=models.Value(2)), models.When(bracket_tag='E', then=models.Value(1)), default=models.Value(0)), output_field=models.PositiveSmallIntegerField(help_text='Bracket number based on the tag')),
        ),
        migrations.AlterField(
            model_name='variant',
            name='bracket_tag',
            field=models.CharField(choices=[('R', 'Ruthless'), ('S', 'Spicy'), ('P', 'Powerful'), ('O', 'Oddball'), ('C', 'Core'), ('E', 'Exhibition')], default='R', editable=False, help_text='Bracket tag for this variant', max_length=2),
        ),
        migrations.AlterField(
            model_name='variant',
            name='bracket_tag_override',
            field=models.CharField(blank=True, choices=[('R', 'Ruthless'), ('S', 'Spicy'), ('P', 'Powerful'), ('O', 'Oddball'), ('C', 'Core'), ('E', 'Exhibition')], help_text='Override bracket tag for this variant', max_length=2, null=True),
        ),
        migrations.RunPython(rename_bracket_tags, reverse_code=reverse_rename_bracket_tags),
    ]
