# Generated by Django 6.0.2 on 2026-03-09 11:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0060_remove_variant_bracket_tag_override_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='layout_rotation_front',
            field=models.CharField(blank=True, choices=[('clockwise', 'Clockwise'), ('counterclockwise', 'Counterclockwise'), ('flip', 'Flip')], max_length=20, null=True, verbose_name='layout rotation of the front of the card'),
        ),
    ]
