# Generated by Django 6.0.7 on 2026-07-15 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0063_alter_cardincombo_battlefield_card_state_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='VariantGenerationFingerprints',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(help_text='Entity kind these fingerprints belong to', max_length=32, unique=True)),
                ('fingerprints', models.JSONField(help_text='Mapping of entity id to input fingerprint hash')),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'variant generation fingerprints',
                'verbose_name_plural': 'variant generation fingerprints',
                'default_manager_name': 'objects',
            },
        ),
    ]
