# Generated by Django 6.0.7 on 2026-07-24 13:39

import django.core.validators
from django.db import migrations, models


def set_faces_from_name(apps, schema_editor):
    '''Split cards contain " // " in their name: the number of faces is the number of separators plus one.'''
    Card = apps.get_model('spellbook', 'Card')
    separator = ' // '
    cards = list(Card.objects.filter(name__contains=separator).only('id', 'name'))
    for card in cards:
        card.faces = card.name.count(separator) + 1
    Card.objects.bulk_update(cards, ['faces'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0064_variantgenerationfingerprints_and_quantity_max'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='faces',
            field=models.PositiveSmallIntegerField(default=1, help_text='Number of faces (subcards) this card is split into, such as double-faced cards, adventures, split cards and so on. 1 for normal cards.', validators=[django.core.validators.MinValueValidator(1)], verbose_name='number of faces of card'),
        ),
        migrations.RunPython(set_faces_from_name, migrations.RunPython.noop),
        migrations.AddField(
            model_name='cardincombo',
            name='used_face',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='For multi-faced cards (double-faced, adventures, split cards...), the 1-based index of the face actually used. Leave blank to use the whole card.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='used face'),
        ),
        migrations.AddField(
            model_name='cardinvariant',
            name='used_face',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='For multi-faced cards (double-faced, adventures, split cards...), the 1-based index of the face actually used. Leave blank to use the whole card.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='used face'),
        ),
        migrations.AddField(
            model_name='featureofcard',
            name='used_face',
            field=models.PositiveSmallIntegerField(blank=True, default=None, help_text='For multi-faced cards (double-faced, adventures, split cards...), the 1-based index of the face actually used. Leave blank to use the whole card.', null=True, validators=[django.core.validators.MinValueValidator(1)], verbose_name='used face'),
        ),
    ]
