# Generated by Django 6.0.7 on 2026-08-03 11:35

import django.core.validators
from django.db import migrations, models
from spellbook.models.utils import DEFAULT_BATCH_SIZE


def populate_order_field(apps, schema_editor):
    # Numbering by id keeps the order the rows already had, when it was implied by their creation order
    FeatureNeededInCombo = apps.get_model('spellbook', 'FeatureNeededInCombo')
    rows = list(FeatureNeededInCombo.objects.order_by('combo_id', 'id').only('id', 'combo_id', 'order'))
    order_by_combo = dict[int, int]()
    for row in rows:
        order_by_combo[row.combo_id] = order_by_combo.get(row.combo_id, 0) + 1
        row.order = order_by_combo[row.combo_id]
    FeatureNeededInCombo.objects.bulk_update(rows, ['order'], batch_size=DEFAULT_BATCH_SIZE)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0065_faces_and_used_face'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='featureneededincombo',
            options={'ordering': ['order', 'id']},
        ),
        migrations.AddField(
            model_name='featureneededincombo',
            name='order',
            field=models.PositiveIntegerField(db_index=True, default=0, help_text='Order of the card in the combo.', verbose_name='order'),
        ),
        migrations.RunPython(populate_order_field, migrations.RunPython.noop, elidable=True),
        migrations.AlterField(
            model_name='featureattribute',
            name='name',
            field=models.CharField(help_text='Name of the attribute, usable to select a feature replacement with the [[feature$attribute]] syntax', max_length=255, unique=True, validators=[django.core.validators.RegexValidator(inverse_match=True, message='Reserved characters are not allowed. Examples of reserved characters: $, |.', regex='\\$|\\|')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, help_text='Long description of the combo, in steps. Here and in every other text field you can reference feature replacements with the [[name]] syntax. Optionally, you can also give it an alias to use later with [[name|alias]] and/or select one of the multiple copies with [[name$number]], where the number is the position of the needed feature row among the ones this combo needs for that feature, or with [[name$attribute]], where the attribute is the name of one of the attributes the feature was produced with.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\})*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
    ]
