# Generated by Django 6.0.7 on 2026-08-06 14:15

import django.contrib.postgres.indexes
import django.db.models.functions.comparison
import django.db.models.functions.text
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0066_featureneededincombo_order'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='card',
            name='card_keywords_trgm_idx',
        ),
        migrations.RemoveIndex(
            model_name='template',
            name='card_template_name_index',
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper(django.db.models.functions.comparison.Cast('keywords', models.TextField())), name='gin_trgm_ops'), name='card_keywords_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('battlefield_card_state'), name='gin_trgm_ops'), name='cic_battlefield_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('exile_card_state'), name='gin_trgm_ops'), name='cic_exile_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('graveyard_card_state'), name='gin_trgm_ops'), name='cic_graveyard_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='cardincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('library_card_state'), name='gin_trgm_ops'), name='cic_library_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('mana_needed'), name='gin_trgm_ops'), name='combo_mana_needed_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='combo_description_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('notes'), name='gin_trgm_ops'), name='combo_notes_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('comment'), name='gin_trgm_ops'), name='combo_comment_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('easy_prerequisites'), name='gin_trgm_ops'), name='combo_easy_prereq_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('notable_prerequisites'), name='gin_trgm_ops'), name='combo_notable_prereq_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureneededincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('battlefield_card_state'), name='gin_trgm_ops'), name='fnic_battlefield_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureneededincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('exile_card_state'), name='gin_trgm_ops'), name='fnic_exile_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureneededincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('graveyard_card_state'), name='gin_trgm_ops'), name='fnic_graveyard_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureneededincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('library_card_state'), name='gin_trgm_ops'), name='fnic_library_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('battlefield_card_state'), name='gin_trgm_ops'), name='foc_battlefield_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('exile_card_state'), name='gin_trgm_ops'), name='foc_exile_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('graveyard_card_state'), name='gin_trgm_ops'), name='foc_graveyard_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('library_card_state'), name='gin_trgm_ops'), name='foc_library_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('mana_needed'), name='gin_trgm_ops'), name='foc_mana_needed_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('easy_prerequisites'), name='gin_trgm_ops'), name='foc_easy_prereq_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('notable_prerequisites'), name='gin_trgm_ops'), name='foc_notable_prereq_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='templateincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('battlefield_card_state'), name='gin_trgm_ops'), name='tic_battlefield_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='templateincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('exile_card_state'), name='gin_trgm_ops'), name='tic_exile_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='templateincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('graveyard_card_state'), name='gin_trgm_ops'), name='tic_graveyard_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='templateincombo',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('library_card_state'), name='gin_trgm_ops'), name='tic_library_trgm_idx'),
        ),
    ] if connection.vendor == 'postgresql' else []
