# Generated by Django 6.0.7 on 2026-08-17 14:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0067_reference_trigram_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='cardincombo',
            name='in_replacements',
            field=models.BooleanField(default=True, help_text='Does this ingredient take part in the replacements of the features this combo produces? Unchecking it leaves the ingredient out of the replacement texts, and out of the starting state and location overrides too.', verbose_name='in replacements'),
        ),
        migrations.AddField(
            model_name='featureneededincombo',
            name='in_replacements',
            field=models.BooleanField(default=True, help_text='Does this ingredient take part in the replacements of the features this combo produces? Unchecking it leaves the ingredient out of the replacement texts, and out of the starting state and location overrides too.', verbose_name='in replacements'),
        ),
        migrations.AddField(
            model_name='templateincombo',
            name='in_replacements',
            field=models.BooleanField(default=True, help_text='Does this ingredient take part in the replacements of the features this combo produces? Unchecking it leaves the ingredient out of the replacement texts, and out of the starting state and location overrides too.', verbose_name='in replacements'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, help_text='Long description of the combo, in steps. Here and in every other text field you can reference feature replacements with the [[name]] syntax. Optionally, you can also give it an alias to use later with [[name|alias]] and/or select one of the multiple copies with [[name$number]], where the number is the position of the needed feature row among the ones this combo needs for that feature, or with [[name$attribute]], where the attribute is the name of one of the attributes the feature was produced with. Uncheck "in replacements" on an ingredient to keep it out of the replacements of the features this combo produces.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\})*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
    ]
