# Generated by Django 6.0.7 on 2026-08-19 18:39

from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0069_used_face_from_card_states'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_4f1cc9_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_b_514b08_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_c_ddc9a2_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_l_d430ec_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_m_1a9579_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_o_b2a940_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_337707_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_13ffb6_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_0e5738_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_98cf13_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_d26723_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_p_db6e3f_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_s_d98dd9_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_v_5749a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_a_36c23c_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_c_13b874_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_legal_s_8ee71b_idx',
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_alchemy'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_alchemy_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_brawl'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_brawl_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_commander'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_commander_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_competitive_brawl'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_comp_brawl_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_legacy'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_legacy_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_modern'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_modern_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_oathbreaker'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_oathbreaker_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_pauper'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_pauper_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_pauper_commander'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_pdh_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_pauper_commander_main'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_pdh_main_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_pioneer'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_pioneer_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_predh'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_predh_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_premodern'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_premodern_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_standard'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_standard_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_standard_brawl'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_standard_brawl_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('legal_vintage'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_vintage_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('identity'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_identity_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('hulkline'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_hulkline_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('result_count'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), models.F('id'), name='variant_rc_view_ordering_idx'),
        ),
    ] if connection.vendor == 'postgresql' else [
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['hulkline'], name='spellbook_v_hulklin_9d248c_idx'),
        ),
    ]
