# Generated by Django 6.0.7 on 2026-08-20 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0070_view_ordering_indexes'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['variant_count'], name='spellbook_c_variant_50e87a_idx'),
        ),
    ]
