# Generated by Django 6.0.7 on 2026-09-01 12:44

from django.db import migrations, models
from spellbook.models.variant_counts import recompute_all_counts


def backfill_counts(apps, schema_editor):
    recompute_all_counts()


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0071_combo_variant_count_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='combo',
            name='public_variant_count',
            field=models.PositiveIntegerField(default=0, editable=False, help_text='Number of variants of this combo that are public'),
        ),
        migrations.AddIndex(
            model_name='combo',
            index=models.Index(fields=['public_variant_count'], name='spellbook_c_public__024430_idx'),
        ),
        migrations.RunPython(backfill_counts, migrations.RunPython.noop, elidable=True),
    ]
