# Generated by Django 6.0.7 on 2026-09-08 07:12

import django.contrib.postgres.indexes
import django.core.validators
import django.db.models.functions.text
from django.db import migrations, models, connection


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0072_public_variant_count_and_curly_references'),
    ]

    operations = [
        migrations.AddField(
            model_name='featureofcard',
            name='comment',
            field=models.TextField(blank=True, help_text='Notes for the editors, not displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AddField(
            model_name='featureofcard',
            name='description',
            field=models.TextField(blank=True, help_text='Long description, in steps. Here and in every other text field you can reference feature replacements with the [[name]] syntax. Optionally, you can also give it an alias to use later with [[name|alias]] and/or select one of the multiple copies with [[name$number]], where the number is the position of the needed feature row among the ones this combo needs for that feature, or with [[name$attribute]], where the attribute is the name of one of the attributes the feature was produced with. Uncheck "in replacements" on an ingredient to keep it out of the replacements of the features this combo produces. With the {{name}} syntax, and the same selectors, you can instead write here the text of this same field, taken from every combo or card producing that feature: those texts are then not appended to this one, because they have already been written where you mentioned them.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AddField(
            model_name='featureofcard',
            name='is_mana_needed_an_accurate_minimum',
            field=models.BooleanField(default=True, help_text='Does the first mana cost in this field represent the MINIMUM needed to start, ignoring all other text?'),
        ),
        migrations.AddField(
            model_name='featureofcard',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes that will be displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='comment',
            field=models.TextField(blank=True, help_text='Notes for the editors, not displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='description',
            field=models.TextField(blank=True, help_text='Long description, in steps. Here and in every other text field you can reference feature replacements with the [[name]] syntax. Optionally, you can also give it an alias to use later with [[name|alias]] and/or select one of the multiple copies with [[name$number]], where the number is the position of the needed feature row among the ones this combo needs for that feature, or with [[name$attribute]], where the attribute is the name of one of the attributes the feature was produced with. Uncheck "in replacements" on an ingredient to keep it out of the replacements of the features this combo produces. With the {{name}} syntax, and the same selectors, you can instead write here the text of this same field, taken from every combo or card producing that feature: those texts are then not appended to this one, because they have already been written where you mentioned them.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='easy_prerequisites',
            field=models.TextField(blank=True, help_text='Easily achievable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='is_mana_needed_an_accurate_minimum',
            field=models.BooleanField(default=True, help_text='Does the first mana cost in this field represent the MINIMUM needed to start, ignoring all other text?'),
        ),
        migrations.AlterField(
            model_name='combo',
            name='mana_needed',
            field=models.CharField(blank=True, help_text='Mana needed. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=512, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format, and must start with mana symbols, but can contain normal text later.', regex='^(?:(?:\\{(?:C\\/[WUBRG]|[WUBRG](?:\\/P)?|[0-9CPXYZS∞]|[1-9][0-9]{1,2}|(?:2\\/[WUBRG]|W\\/U|W\\/B|U\\/B|U\\/R|B\\/R|B\\/G|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?)\\})[^\\{\\}]*)*$'), django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='notable_prerequisites',
            field=models.TextField(blank=True, help_text='Notable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='combo',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes that will be displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='featureofcard',
            name='easy_prerequisites',
            field=models.TextField(blank=True, help_text='Easily achievable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='featureofcard',
            name='mana_needed',
            field=models.CharField(blank=True, help_text='Mana needed. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=512, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format, and must start with mana symbols, but can contain normal text later.', regex='^(?:(?:\\{(?:C\\/[WUBRG]|[WUBRG](?:\\/P)?|[0-9CPXYZS∞]|[1-9][0-9]{1,2}|(?:2\\/[WUBRG]|W\\/U|W\\/B|U\\/B|U\\/R|B\\/R|B\\/G|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?)\\})[^\\{\\}]*)*$'), django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='featureofcard',
            name='notable_prerequisites',
            field=models.TextField(blank=True, help_text='Notable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='comment',
            field=models.TextField(blank=True, help_text='Notes for the editors, not displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='description',
            field=models.TextField(blank=True, help_text='Long description, in steps. Here and in every other text field you can reference feature replacements with the [[name]] syntax. Optionally, you can also give it an alias to use later with [[name|alias]] and/or select one of the multiple copies with [[name$number]], where the number is the position of the needed feature row among the ones this combo needs for that feature, or with [[name$attribute]], where the attribute is the name of one of the attributes the feature was produced with. Uncheck "in replacements" on an ingredient to keep it out of the replacements of the features this combo produces. With the {{name}} syntax, and the same selectors, you can instead write here the text of this same field, taken from every combo or card producing that feature: those texts are then not appended to this one, because they have already been written where you mentioned them.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='easy_prerequisites',
            field=models.TextField(blank=True, help_text='Easily achievable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_mana_needed_an_accurate_minimum',
            field=models.BooleanField(default=True, help_text='Does the first mana cost in this field represent the MINIMUM needed to start, ignoring all other text?'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='mana_needed',
            field=models.CharField(blank=True, help_text='Mana needed. Use the {1}{W}{U}{B}{R}{G}{B/P}... format.', max_length=512, validators=[django.core.validators.RegexValidator(message='Mana needed must be in the {1}{W}{U}{B}{R}{G}{B/P}... format, and must start with mana symbols, but can contain normal text later.', regex='^(?:(?:\\{(?:C\\/[WUBRG]|[WUBRG](?:\\/P)?|[0-9CPXYZS∞]|[1-9][0-9]{1,2}|(?:2\\/[WUBRG]|W\\/U|W\\/B|U\\/B|U\\/R|B\\/R|B\\/G|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?)\\})[^\\{\\}]*)*$'), django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='notable_prerequisites',
            field=models.TextField(blank=True, help_text='Notable prerequisites.', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
        migrations.AlterField(
            model_name='variant',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes that will be displayed on the site', validators=[django.core.validators.RegexValidator(message='Unpaired double square brackets are not allowed.', regex='^(?:[^\\[]*(?:\\[(?!\\[)|\\[{2}[^\\[]+\\]{2}|\\[{3,}))*[^\\[]*$'), django.core.validators.RegexValidator(message='Unpaired double curly brackets are not allowed.', regex='^(?:[^\\{]*(?:\\{(?!\\{)|\\{{2}[^\\{]+\\}{2}|\\{{3,}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Symbols must be in the {1}{W}{U}{B}{R}{G}{B/P}{A}{E}{T}{Q}... format.', regex='^(?:[^\\{]*(?:\\{(?:(?:2\\/[WUBRG]|W\\/U|W\\/B|B\\/R|B\\/G|U\\/B|U\\/R|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?|CHAOS|PW|TK|[WUBRG](?:\\/P)?|[1-9][0-9]{1,2}|H[WUBRG]|[0-9CPXYZSTQEA½∞])\\}|\\{\\{[^\\{\\}]+\\}\\}))*[^\\{]*$'), django.core.validators.RegexValidator(message='Only ordinary characters are allowed.', regex='^[\\x0A\\x0D\\x20-\\x7E\\x80\\x95\\x99\\xA1\\xA9\\xAE\\xB0\\xB1-\\xB3\\xBC-\\xFF\\u0100-\\u024F\\u0300-\\u036F\\u1E00-\\u1EFF\\u2014\\uA720-\\uA7FF]*$')]),
        ),
    ] + ([
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('description'), name='gin_trgm_ops'), name='foc_description_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('notes'), name='gin_trgm_ops'), name='foc_notes_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='featureofcard',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('comment'), name='gin_trgm_ops'), name='foc_comment_trgm_idx'),
        ),
    ] if connection.vendor == 'postgresql' else [])
