# Generated by Django 6.0.7 on 2026-09-08 22:18

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.db.models.functions.comparison
import django.db.models.functions.text
import spellbook.models.fields
import spellbook.parsers.lark_validator
import spellbook.parsers.safe_regex
from django.db import migrations, models, connection
from django.db.models import Exists, OuterRef, Q
from spellbook.models.variant import EXTRA_TURN_FOR_OPPONENT_PATTERN, EXTRA_TURN_PATTERN, MASS_LAND_DENIAL_PATTERN
from ._utils import card_number_from_id, normalize_card_names


def populate_card_property_flags(apps, schema_editor):
    '''Fills the flags in for the variants that already exist, the way generation now computes them.'''
    Variant = apps.get_model('spellbook', 'Variant')
    Card = apps.get_model('spellbook', 'Card')
    FeatureProducedByVariant = apps.get_model('spellbook', 'FeatureProducedByVariant')
    for flag in ('tutor', 'game_changer', 'reserved'):
        Variant.objects.filter(
            Exists(Card.objects.filter(cardinvariant__variant_id=OuterRef('pk'), **{flag: True}))
        ).update(**{flag: True})
    produced = {
        'mass_land_denial': Q(feature__name__iregex=MASS_LAND_DENIAL_PATTERN.pattern),
        'extra_turn': Q(feature__name__iregex=EXTRA_TURN_PATTERN.pattern) & ~Q(feature__name__iregex=EXTRA_TURN_FOR_OPPONENT_PATTERN.pattern),
    }
    for flag, condition in produced.items():
        Variant.objects.filter(
            Exists(FeatureProducedByVariant.objects.filter(condition, variant_id=OuterRef('pk')))
        ).update(**{flag: True})


def remove_content_types_of_deleted_models(apps, schema_editor):
    '''Drops the content types of the spellbook models earlier migrations deleted, and the permissions
    cascading off them: deleting a model leaves both behind, so they outlive it by whole releases and
    keep being offered in the admin.'''
    ContentType = apps.get_model('contenttypes', 'ContentType')
    Permission = apps.get_model('auth', 'Permission')
    database = schema_editor.connection.alias
    stale = ContentType.objects.using(database).filter(app_label='spellbook').exclude(model__in=apps.all_models['spellbook'])
    Permission.objects.using(database).filter(content_type__in=stale).delete()
    stale.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0073_featureofcard_comment_featureofcard_description_and_more'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0002_alter_permission_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='CardOracleTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'card oracle tag',
                'verbose_name_plural': 'card oracle tags',
            },
        ),
        migrations.CreateModel(
            name='OracleTag',
            fields=[
                ('id', models.UUIDField(primary_key=True, serialize=False, verbose_name='Scryfall ID of tag')),
                ('slug', models.CharField(max_length=255, unique=True, verbose_name='slug of tag')),
                ('label', models.CharField(blank=True, max_length=255, verbose_name='label of tag')),
                ('description', models.TextField(blank=True, verbose_name='description of tag')),
            ],
            options={
                'verbose_name': 'oracle tag',
                'verbose_name_plural': 'oracle tags',
                'ordering': ['slug'],
            },
        ),
        migrations.CreateModel(
            name='OracleTagName',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='name of tag')),
                ('normalized_name', models.CharField(max_length=255, unique=True, verbose_name='normalized name of tag')),
            ],
            options={
                'verbose_name': 'oracle tag name',
                'verbose_name_plural': 'oracle tag names',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='TemplateMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
            options={
                'verbose_name': 'template match',
                'verbose_name_plural': 'template matches',
            },
        ),
        migrations.AddField(
            model_name='card',
            name='layout',
            field=models.CharField(blank=True, help_text='Scryfall layout of the card, such as normal, transform or adventure', max_length=32, verbose_name='layout of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='loyalty',
            field=models.CharField(blank=True, help_text='Starting loyalty of the card, which can be a value such as X', max_length=16, verbose_name='loyalty of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='loyalty_value',
            field=models.IntegerField(blank=True, help_text='Loyalty as a number, when it is one, so that a search can compare it', null=True, verbose_name='numeric loyalty of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='mana_cost',
            field=models.CharField(blank=True, help_text='Mana cost of the card, in the {1}{W}{U} format', max_length=128, verbose_name='mana cost of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='number',
            field=models.BigIntegerField(blank=True, editable=False, help_text='Compact identifier of a card an editor has curated, and the only way other models reference it', null=True, unique=True, verbose_name='card number'),
        ),
        migrations.AddField(
            model_name='card',
            name='power',
            field=models.CharField(blank=True, help_text='Power of the card, which can be a value such as * or 1+*', max_length=16, verbose_name='power of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='power_value',
            field=models.IntegerField(blank=True, help_text='Power as a number, when it is one, so that a search can compare it', null=True, verbose_name='numeric power of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='produced_mana',
            field=spellbook.models.fields.KeywordsField(default=list, verbose_name='mana produced by card'),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness',
            field=models.CharField(blank=True, help_text='Toughness of the card, which can be a value such as * or 1+*', max_length=16, verbose_name='toughness of card'),
        ),
        migrations.AddField(
            model_name='card',
            name='toughness_value',
            field=models.IntegerField(blank=True, help_text='Toughness as a number, when it is one, so that a search can compare it', null=True, verbose_name='numeric toughness of card'),
        ),
        migrations.RunPython(card_number_from_id, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='cardincombo',
            name='card',
            field=models.ForeignKey(limit_choices_to={'number__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='spellbook.card', to_field='number'),
        ),
        migrations.AlterField(
            model_name='cardinvariant',
            name='card',
            field=models.ForeignKey(limit_choices_to={'number__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='spellbook.card', to_field='number'),
        ),
        migrations.AlterField(
            model_name='featureofcard',
            name='card',
            field=models.ForeignKey(limit_choices_to={'number__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='spellbook.card', to_field='number'),
        ),
        migrations.AlterField(
            model_name='template',
            name='scryfall_query',
            field=models.CharField(blank=True, help_text='Variables supported: mv, manavalue, power, pow, toughness, tou, pt, powtou, loyalty, loy, c, color, id, identity, produces, has, t, type, keyword, kw, is, o, oracle, function, otag, oracletag, oracleid, m, mana, devotion.\nOperators supported: =, !=, <, >, <=, >=, :.\nYou can compose a "and"/"or" expression made of "and"/"or" expressions, like "(c:W or c:U) and (t:creature or t:artifact)".\nYou can also omit parentheses when not necessary, like "(c:W or c:U) t:creature".\nCard names are only supported if wrapped in double quotes and preceded by an exclamation mark (!) in order to match the exact name, like !"Lightning Bolt".\nYou can negate any expression by prepending a dash (-), like "-t:creature".\nA regular expression must be at most 256 characters long, and may not repeat a group\nthat repeats or chooses within itself, since that can take exponential time to match.\nMore info at: https://scryfall.com/docs/syntax.\n', max_length=1024, null=True, validators=[spellbook.parsers.lark_validator.LarkGrammarValidator('%import common.WS -> _WS\n%import common.SIGNED_INT -> INTEGER\n\n?start : expression\n\n?expression : term | expression OR term -> or_expression\n\n?term : factor | term (AND | _WS) factor -> and_expression\n\n?factor : matcher | group\n\n?matcher: value | NEGATION_OPERATOR value -> negation\n\ngroup : LPAREN expression RPAREN\n    | NEGATION_OPERATOR LPAREN expression RPAREN -> negated_group\n\n?value: exact_name | pair\n\nexact_name : "!" LONG_LITERAL\n\n?pair : COMPARABLE_STRING_VARIABLE COMPARISON_OPERATOR string_value -> comparable_string_pair\n    | NUMERIC_VARIABLE COMPARISON_OPERATOR numeric_value -> numeric_pair\n    | MANA_VARIABLE COMPARISON_OPERATOR mana_value -> mana_pair\n    | UNCOMPARABLE_STRING_VARIABLE ":" string_value -> uncomparable_string_pair\n\n?string_value : SHORT_LITERAL | LONG_LITERAL | REGEX_VALUE\n\n?numeric_value : INTEGER | NUMERIC_VARIABLE\n\n?mana_value : INTEGER | mana_expression\n\nmana_expression : MANA_SYMBOL+\n\nLONG_LITERAL.10 : /"[^"]+"/\n\nOR.9 : " OR " | " or "\n\nAND.9 : " AND " | " and " | " && "\n\nLPAREN.9 : "("\n\nRPAREN.9 : ")"\n\nSHORT_LITERAL.-1 : /[^\\/\\s:<>!="()][^\\s:<>!="()]*/\n\nREGEX_VALUE : /\\/(?:\\\\\\/|[^\\/])+\\//\n\nNEGATION_OPERATOR : "-"\n\n        MANA_SYMBOL.5 : /\\{(?:C\\/[WUBRG]|[WUBRG](?:\\/P)?|[0-9CPXYZS∞]|[1-9][0-9]{1,2}|(?:2\\/[WUBRG]|W\\/U|W\\/B|U\\/B|U\\/R|B\\/R|B\\/G|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?)\\}/\n        COMPARISON_OPERATOR : "=" | "!=" | "<" | ">" | "<=" | ">=" | ":"\n        NUMERIC_VARIABLE.4 : "mv" | "manavalue" | "power" | "pow" | "toughness" | "tou" | "pt" | "powtou" | "loyalty" | "loy"\n        MANA_VARIABLE.3 : "m" | "mana" | "devotion"\n        COMPARABLE_STRING_VARIABLE.2 : "c" | "color" | "id" | "identity" | "produces"\n        UNCOMPARABLE_STRING_VARIABLE.1 : "has" | "t" | "type" | "keyword" | "kw" | "is" | "o" | "oracle" | "function" | "otag" | "oracletag" | "oracleid"\n    '), spellbook.parsers.safe_regex.validate_query_regexes], verbose_name='Scryfall query'),
        ),
        migrations.AlterField(
            model_name='templatereplacement',
            name='card',
            field=models.ForeignKey(limit_choices_to={'number__isnull': False}, on_delete=django.db.models.deletion.CASCADE, to='spellbook.card', to_field='number'),
        ),
        migrations.AlterField(
            model_name='templaterequiredinvariantsuggestion',
            name='scryfall_query',
            field=models.CharField(blank=True, help_text='Variables supported: mv, manavalue, power, pow, toughness, tou, pt, powtou, loyalty, loy, c, color, id, identity, produces, has, t, type, keyword, kw, is, o, oracle, function, otag, oracletag, oracleid, m, mana, devotion.\nOperators supported: =, !=, <, >, <=, >=, :.\nYou can compose a "and"/"or" expression made of "and"/"or" expressions, like "(c:W or c:U) and (t:creature or t:artifact)".\nYou can also omit parentheses when not necessary, like "(c:W or c:U) t:creature".\nCard names are only supported if wrapped in double quotes and preceded by an exclamation mark (!) in order to match the exact name, like !"Lightning Bolt".\nYou can negate any expression by prepending a dash (-), like "-t:creature".\nA regular expression must be at most 256 characters long, and may not repeat a group\nthat repeats or chooses within itself, since that can take exponential time to match.\nMore info at: https://scryfall.com/docs/syntax.\n', max_length=1024, null=True, validators=[spellbook.parsers.lark_validator.LarkGrammarValidator('%import common.WS -> _WS\n%import common.SIGNED_INT -> INTEGER\n\n?start : expression\n\n?expression : term | expression OR term -> or_expression\n\n?term : factor | term (AND | _WS) factor -> and_expression\n\n?factor : matcher | group\n\n?matcher: value | NEGATION_OPERATOR value -> negation\n\ngroup : LPAREN expression RPAREN\n    | NEGATION_OPERATOR LPAREN expression RPAREN -> negated_group\n\n?value: exact_name | pair\n\nexact_name : "!" LONG_LITERAL\n\n?pair : COMPARABLE_STRING_VARIABLE COMPARISON_OPERATOR string_value -> comparable_string_pair\n    | NUMERIC_VARIABLE COMPARISON_OPERATOR numeric_value -> numeric_pair\n    | MANA_VARIABLE COMPARISON_OPERATOR mana_value -> mana_pair\n    | UNCOMPARABLE_STRING_VARIABLE ":" string_value -> uncomparable_string_pair\n\n?string_value : SHORT_LITERAL | LONG_LITERAL | REGEX_VALUE\n\n?numeric_value : INTEGER | NUMERIC_VARIABLE\n\n?mana_value : INTEGER | mana_expression\n\nmana_expression : MANA_SYMBOL+\n\nLONG_LITERAL.10 : /"[^"]+"/\n\nOR.9 : " OR " | " or "\n\nAND.9 : " AND " | " and " | " && "\n\nLPAREN.9 : "("\n\nRPAREN.9 : ")"\n\nSHORT_LITERAL.-1 : /[^\\/\\s:<>!="()][^\\s:<>!="()]*/\n\nREGEX_VALUE : /\\/(?:\\\\\\/|[^\\/])+\\//\n\nNEGATION_OPERATOR : "-"\n\n        MANA_SYMBOL.5 : /\\{(?:C\\/[WUBRG]|[WUBRG](?:\\/P)?|[0-9CPXYZS∞]|[1-9][0-9]{1,2}|(?:2\\/[WUBRG]|W\\/U|W\\/B|U\\/B|U\\/R|B\\/R|B\\/G|R\\/G|R\\/W|G\\/W|G\\/U)(?:\\/P)?)\\}/\n        COMPARISON_OPERATOR : "=" | "!=" | "<" | ">" | "<=" | ">=" | ":"\n        NUMERIC_VARIABLE.4 : "mv" | "manavalue" | "power" | "pow" | "toughness" | "tou" | "pt" | "powtou" | "loyalty" | "loy"\n        MANA_VARIABLE.3 : "m" | "mana" | "devotion"\n        COMPARABLE_STRING_VARIABLE.2 : "c" | "color" | "id" | "identity" | "produces"\n        UNCOMPARABLE_STRING_VARIABLE.1 : "has" | "t" | "type" | "keyword" | "kw" | "is" | "o" | "oracle" | "function" | "otag" | "oracletag" | "oracleid"\n    '), spellbook.parsers.safe_regex.validate_query_regexes], verbose_name='Scryfall query'),
        ),
        migrations.RunPython(normalize_card_names, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(django.db.models.functions.text.Lower('name'), name='card_lower_name_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(django.db.models.functions.text.Lower('name_unaccented'), name='card_lower_name_unacc_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['mana_cost'], name='spellbook_c_mana_co_4237d3_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['power_value'], name='spellbook_c_power_v_f5823f_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['toughness_value'], name='spellbook_c_toughne_086e14_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=models.Index(fields=['loyalty_value'], name='spellbook_c_loyalty_9453c0_idx'),
        ),
        migrations.AddField(
            model_name='cardoracletag',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.card'),
        ),
        migrations.AddField(
            model_name='oracletag',
            name='cards',
            field=models.ManyToManyField(related_name='oracle_tags', through='spellbook.CardOracleTag', to='spellbook.card', verbose_name='cards carrying the tag'),
        ),
        migrations.AddField(
            model_name='cardoracletag',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.oracletag'),
        ),
        migrations.AddField(
            model_name='oracletagname',
            name='tag',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='names', to='spellbook.oracletag'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.card'),
        ),
        migrations.AddField(
            model_name='templatematch',
            name='template',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='spellbook.template'),
        ),
        migrations.AddField(
            model_name='template',
            name='matches',
            field=models.ManyToManyField(editable=False, help_text='Cards this template stands for, whether its query found them or an editor listed them', related_name='matched_by', through='spellbook.TemplateMatch', to='spellbook.card', verbose_name='cards matching template'),
        ),
        migrations.AddIndex(
            model_name='cardoracletag',
            index=models.Index(fields=['tag', 'card'], name='spellbook_c_tag_id_9ab99d_idx'),
        ),
        migrations.AddConstraint(
            model_name='cardoracletag',
            constraint=models.UniqueConstraint(fields=('card', 'tag'), name='unique_card_oracle_tag'),
        ),
        migrations.AddIndex(
            model_name='templatematch',
            index=models.Index(fields=['template', 'card'], name='spellbook_t_templat_8b94bb_idx'),
        ),
        migrations.AddConstraint(
            model_name='templatematch',
            constraint=models.UniqueConstraint(fields=('card', 'template'), name='unique_template_match'),
        ),
        migrations.AddField(
            model_name='variant',
            name='extra_turn',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant produces extra turns for its controller'),
        ),
        migrations.AddField(
            model_name='variant',
            name='game_changer',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant uses a card in the official Game Changer card list'),
        ),
        migrations.AddField(
            model_name='variant',
            name='mass_land_denial',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant produces mass land denial'),
        ),
        migrations.AddField(
            model_name='variant',
            name='reserved',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant uses a card on the Reserved List'),
        ),
        migrations.AddField(
            model_name='variant',
            name='tutor',
            field=models.BooleanField(default=False, editable=False, help_text='Whether the variant uses a card that can tutor for other cards'),
        ),
        migrations.RunPython(populate_card_property_flags, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(remove_content_types_of_deleted_models, migrations.RunPython.noop, elidable=True),
    ] + ([
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper('mana_cost'), name='gin_trgm_ops'), name='card_mana_cost_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='card',
            index=django.contrib.postgres.indexes.GinIndex(django.contrib.postgres.indexes.OpClass(django.db.models.functions.text.Upper(django.db.models.functions.comparison.Cast('produced_mana', models.TextField())), name='gin_trgm_ops'), name='card_produced_mana_trgm_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('tutor'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_tutor_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('game_changer'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_game_changer_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('reserved'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_reserved_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('mass_land_denial'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_mld_pop_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(models.F('extra_turn'), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), name='variant_extra_turn_pop_idx'),
        ),
    ] if connection.vendor == 'postgresql' else [
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['tutor'], name='spellbook_v_tutor_4fbc54_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['game_changer'], name='spellbook_v_game_ch_d3c5ee_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['reserved'], name='spellbook_v_reserve_fa472c_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['mass_land_denial'], name='spellbook_v_mass_la_08c375_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['extra_turn'], name='spellbook_v_extra_t_011f84_idx'),
        ),
    ])
