# Generated by Django 6.0.7 on 2026-09-21 18:03

import django.db.models.functions.text
from django.db import connection, migrations, models
from spellbook.models.utils import produced_mana_kinds
from ._utils import LockTables


def produced_mana_to_kinds(apps, schema_editor):
    Card = apps.get_model('spellbook', 'Card')
    cards = [card for card in Card.objects.only('id', 'produced_mana_symbols') if card.produced_mana_symbols]
    for card in cards:
        card.produced_mana = produced_mana_kinds(card.produced_mana_symbols)
    Card.objects.bulk_update(cards, ['produced_mana'], batch_size=1000)


def produced_mana_to_symbols(apps, schema_editor):
    Card = apps.get_model('spellbook', 'Card')
    cards = [card for card in Card.objects.only('id', 'produced_mana') if card.produced_mana]
    for card in cards:
        card.produced_mana_symbols = sorted(card.produced_mana)
    Card.objects.bulk_update(cards, ['produced_mana_symbols'], batch_size=1000)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0075_line_references'),
    ]

    operations = [
        LockTables({
            'Variant': 'ACCESS EXCLUSIVE',
            'Card': 'ACCESS EXCLUSIVE',
        }),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_39f321_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_40e4ef_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_c1138c_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_f101c7_idx',
        ),
        migrations.RemoveIndex(
            model_name='variant',
            name='spellbook_v_identit_cc3c09_idx',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_b',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_g',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_r',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_u',
        ),
        migrations.RemoveField(
            model_name='card',
            name='color_w',
        ),
        migrations.RemoveField(
            model_name='card',
            name='identity_b',
        ),
        migrations.RemoveField(
            model_name='card',
            name='identity_g',
        ),
        migrations.RemoveField(
            model_name='card',
            name='identity_r',
        ),
        migrations.RemoveField(
            model_name='card',
            name='identity_u',
        ),
        migrations.RemoveField(
            model_name='card',
            name='identity_w',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_b',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_g',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_r',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_u',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='color_w',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='identity_b',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='identity_g',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='identity_r',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='identity_u',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='identity_w',
        ),
        *([
            migrations.RemoveIndex(
                model_name='card',
                name='card_produced_mana_trgm_idx',
            ),
        ] if connection.vendor == 'postgresql' else []),
        migrations.RenameField(
            model_name='card',
            old_name='produced_mana',
            new_name='produced_mana_symbols',
        ),
        migrations.AddField(
            model_name='card',
            name='produced_mana',
            field=models.CharField(blank=True, choices=[('', ''), ('W', 'W'), ('U', 'U'), ('B', 'B'), ('R', 'R'), ('G', 'G'), ('WU', 'WU'), ('WB', 'WB'), ('RW', 'RW'), ('GW', 'GW'), ('UB', 'UB'), ('UR', 'UR'), ('GU', 'GU'), ('BR', 'BR'), ('BG', 'BG'), ('RG', 'RG'), ('WUB', 'WUB'), ('URW', 'URW'), ('GWU', 'GWU'), ('RWB', 'RWB'), ('WBG', 'WBG'), ('RGW', 'RGW'), ('UBR', 'UBR'), ('BGU', 'BGU'), ('GUR', 'GUR'), ('BRG', 'BRG'), ('WUBR', 'WUBR'), ('UBRG', 'UBRG'), ('BRGW', 'BRGW'), ('RGWU', 'RGWU'), ('GWUB', 'GWUB'), ('WUBRG', 'WUBRG'), ('C', 'C'), ('WC', 'WC'), ('UC', 'UC'), ('BC', 'BC'), ('RC', 'RC'), ('GC', 'GC'), ('WUC', 'WUC'), ('WBC', 'WBC'), ('RWC', 'RWC'), ('GWC', 'GWC'), ('UBC', 'UBC'), ('URC', 'URC'), ('GUC', 'GUC'), ('BRC', 'BRC'), ('BGC', 'BGC'), ('RGC', 'RGC'), ('WUBC', 'WUBC'), ('URWC', 'URWC'), ('GWUC', 'GWUC'), ('RWBC', 'RWBC'), ('WBGC', 'WBGC'), ('RGWC', 'RGWC'), ('UBRC', 'UBRC'), ('BGUC', 'BGUC'), ('GURC', 'GURC'), ('BRGC', 'BRGC'), ('WUBRC', 'WUBRC'), ('UBRGC', 'UBRGC'), ('BRGWC', 'BRGWC'), ('RGWUC', 'RGWUC'), ('GWUBC', 'GWUBC'), ('WUBRGC', 'WUBRGC')], default='', max_length=6, verbose_name='mana produced by card'),
        ),
        migrations.RunPython(produced_mana_to_kinds, reverse_code=produced_mana_to_symbols),
        migrations.RemoveField(
            model_name='card',
            name='produced_mana_symbols',
        ),
        migrations.AddField(
            model_name='card',
            name='produced_mana_count',
            field=models.GeneratedField(db_persist=True, expression=django.db.models.functions.text.Length('produced_mana'), output_field=models.PositiveSmallIntegerField(default=0, verbose_name='kinds of mana produced by card')),
        ),
        # a rewritten table counts no modified rows, so autovacuum would leave the new column without statistics
        migrations.RunSQL('ANALYZE spellbook_card', reverse_sql=migrations.RunSQL.noop),
    ]
