# Generated by Django 6.0.7 on 2026-09-27 23:49

import django.core.validators
import django.db.models.deletion
from django.apps import apps as global_apps
from django.conf import settings
from django.contrib.auth.management import create_permissions
from django.db import connection, migrations, models
from spellbook.models.utils import DEFAULT_BATCH_SIZE
from ._utils import LockTables


def grant_salt_vote_permissions(apps, schema_editor):
    database = schema_editor.connection.alias
    create_permissions(global_apps.get_app_config('spellbook'), verbosity=0, using=database, apps=apps)
    Permission = apps.get_model('auth', 'Permission')
    User = apps.get_model(settings.AUTH_USER_MODEL)
    UserPermission = User.user_permissions.through
    permissions = list(Permission.objects.using(database).filter(content_type__app_label='spellbook', content_type__model='saltvote').values_list('pk', flat=True))
    UserPermission.objects.using(database).bulk_create(
        [UserPermission(user_id=user, permission_id=permission) for user in User.objects.using(database).values_list('pk', flat=True) for permission in permissions],
        batch_size=DEFAULT_BATCH_SIZE,
        ignore_conflicts=True,
    )


def backfill_salt_in_serialized(apps, schema_editor):
    Variant = apps.get_model('spellbook', 'Variant')
    if schema_editor.connection.vendor == 'postgresql':
        schema_editor.execute(
            f'UPDATE {schema_editor.quote_name(Variant._meta.db_table)} '
            'SET serialized = serialized || \'{"salt": null, "salt_vote_count": 0}\'::jsonb '
            'WHERE serialized IS NOT NULL'
        )
        return
    variants = list(Variant.objects.filter(serialized__isnull=False).only('pk', 'serialized'))
    for variant in variants:
        variant.serialized |= {'salt': None, 'salt_vote_count': 0}
    Variant.objects.bulk_update(variants, ['serialized'], batch_size=DEFAULT_BATCH_SIZE)


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0076_remove_color_flags_add_produced_mana_count'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('auth', '0002_alter_permission_name_max_length'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        LockTables({
            'Variant': 'ACCESS EXCLUSIVE',
        }),
        migrations.AddField(
            model_name='variant',
            name='salt',
            field=models.FloatField(default=None, editable=False, help_text='Average salt score of the recent votes, once they are enough', null=True),
        ),
        migrations.AddField(
            model_name='variant',
            name='salt_vote_count',
            field=models.PositiveIntegerField(db_default=0, default=0, editable=False, help_text='Number of recent salt votes'),
        ),
        *([
            migrations.AddIndex(
                model_name='variant',
                index=models.Index(models.OrderBy(models.F('salt'), descending=True, nulls_last=True), models.OrderBy(models.F('popularity'), descending=True, nulls_last=True), models.OrderBy(models.F('identity_count')), models.OrderBy(models.F('card_count')), models.OrderBy(models.F('created'), descending=True), models.F('id'), name='variant_salt_ordering_idx'),
            ),
        ] if connection.vendor == 'postgresql' else []),
        migrations.CreateModel(
            name='SaltVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveSmallIntegerField(help_text='How salty the variant is, from 0 (not at all) to 4 (the most)', validators=[django.core.validators.MaxValueValidator(4)])),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(db_index=False, editable=False, help_text='User that cast this vote', on_delete=django.db.models.deletion.CASCADE, related_name='salt_votes', to=settings.AUTH_USER_MODEL)),
                ('variant', models.ForeignKey(db_constraint=False, db_index=False, editable=False, help_text='Variant this vote is about', on_delete=django.db.models.deletion.DO_NOTHING, related_name='salt_votes', to='spellbook.variant')),
            ],
            options={
                'verbose_name': 'salt vote',
                'verbose_name_plural': 'salt votes',
                'indexes': [models.Index(fields=['variant', 'updated'], name='spellbook_s_variant_474182_idx')],
                'constraints': [models.UniqueConstraint(fields=('user', 'variant'), name='unique_salt_vote')],
            },
        ),
        migrations.RunPython(grant_salt_vote_permissions, migrations.RunPython.noop, elidable=True),
        migrations.RunPython(backfill_salt_in_serialized, migrations.RunPython.noop, elidable=True),
    ]
