# Generated by Django 6.0.7 on 2026-09-30 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('spellbook', '0077_salt_votes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='variant',
            options={'default_manager_name': 'objects', 'ordering': [models.Case(models.When(status='N', then=models.Value(0)), models.When(status='D', then=models.Value(1)), models.When(status='OK', then=models.Value(2)), models.When(status='E', then=models.Value(3)), models.When(status='RF', then=models.Value(4)), models.When(status='R', then=models.Value(5)), models.When(status='NW', then=models.Value(6)), default=models.Value(10)), '-created', 'id'], 'verbose_name': 'variant', 'verbose_name_plural': 'variants'},
        ),
        migrations.AlterField(
            model_name='variant',
            name='status',
            field=models.CharField(choices=[('N', 'New'), ('D', 'Draft'), ('NR', 'Needs Review'), ('OK', 'Ok'), ('E', 'Example'), ('R', 'Restore'), ('NW', 'Not Working'), ('RF', 'Reference')], db_default='N', help_text='Variant status for editors', max_length=2),
        ),
    ]
