from typing import Generic, Iterable, Iterator, Self, TypeVar
from .multiset import FrozenMultiset

_T = TypeVar('_T')


class MinimalSetOfMultisets(Generic[_T]):
    def __init__(
        self,
        sets: Iterable[FrozenMultiset[_T]] | None = None,
        _internal: set[FrozenMultiset[_T]] | None = None,
    ) -> None: ...
    def subtree(self, under: FrozenMultiset[_T]) -> MinimalSetOfMultisets[_T]: ...
    def add(self, aset: FrozenMultiset[_T]) -> None: ...
    def extend(self, sets: Iterable[FrozenMultiset[_T]]) -> None: ...
    def __iter__(self) -> Iterator[FrozenMultiset[_T]]: ...
    def __len__(self) -> int: ...
    def __contains__(self, aset: FrozenMultiset[_T]) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def __copy__(self) -> Self: ...
    def copy(self) -> Self: ...
    def __or__(self, other: Self) -> Self: ...
