from typing import Hashable, ItemsView, Iterable, KeysView, Mapping, Optional, Self, TypeVar, Union, ValuesView, Generic

_T = TypeVar('_T', bound=Hashable)
_Other = Union['BaseMultiset[_T]', Iterable[_T], Mapping[_T, int]]


class BaseMultiset(Generic[_T]):
    _elements: dict[_T, int]
    _total: int

    def __init__(self, iterable: Optional[_Other[_T]] = None, _internal: Optional[dict[_T, int]] = None) -> None: ...
    def __contains__(self, element: object) -> bool: ...
    def __getitem__(self, element: _T) -> int: ...
    def __str__(self) -> str: ...
    def __repr__(self) -> str: ...
    def __len__(self) -> int: ...
    def isdisjoint(self, other: BaseMultiset[_T]) -> bool: ...
    def difference(self, other: BaseMultiset[_T]) -> Self: ...
    def union(self, other: BaseMultiset[_T]) -> Self: ...
    def combine(self, other: BaseMultiset[_T]) -> Self: ...
    def intersection(self, other: BaseMultiset[_T]) -> Self: ...
    def times(self, factor: int) -> Self: ...
    def count_contains(self, other: BaseMultiset[_T]) -> int: ...
    def issubset(self, other: BaseMultiset[_T]) -> bool: ...
    def issuperset(self, other: BaseMultiset[_T]) -> bool: ...
    def __eq__(self, other: object) -> bool: ...
    def get(self, element: _T, default: int) -> int: ...
    def copy(self) -> Self: ...
    def __copy__(self) -> Self: ...
    def items(self) -> ItemsView[_T, int]: ...
    def distinct_elements(self) -> KeysView[_T]: ...
    def multiplicities(self) -> ValuesView[int]: ...
    def __le__(self, other: BaseMultiset[_T]) -> bool: ...
    def __lt__(self, other: BaseMultiset[_T]) -> bool: ...
    def __ge__(self, other: BaseMultiset[_T]) -> bool: ...
    def __gt__(self, other: BaseMultiset[_T]) -> bool: ...
    def __add__(self, other: BaseMultiset[_T]) -> Self: ...
    def __sub__(self, other: BaseMultiset[_T]) -> Self: ...
    def __mul__(self, factor: int) -> Self: ...
    def __rmul__(self, factor: int) -> Self: ...
    def __or__(self, other: BaseMultiset[_T]) -> Self: ...
    def __and__(self, other: BaseMultiset[_T]) -> Self: ...
    def __floordiv__(self, other: BaseMultiset[_T]) -> int: ...
    __iter__: None


class Multiset(BaseMultiset[_T]):
    def __setitem__(self, element: _T, quantity: int) -> None: ...
    def __delitem__(self, element: _T) -> None: ...
    def add(self, element: _T, quantity: int = 1) -> None: ...


class FrozenMultiset(BaseMultiset[_T]):
    def __hash__(self) -> int: ...
