%import common.WS -> _WS
%import common.SIGNED_INT -> INTEGER

?start : expression

?expression : term | expression OR term -> or_expression

?term : factor | term (AND | _WS) factor -> and_expression

?factor : matcher | group

?matcher: value | NEGATION_OPERATOR value -> negation

group : LPAREN expression RPAREN
    | NEGATION_OPERATOR LPAREN expression RPAREN -> negated_group

?value: exact_name | pair

exact_name : "!" LONG_LITERAL

?pair : COMPARABLE_STRING_VARIABLE COMPARISON_OPERATOR string_value -> comparable_string_pair
    | NUMERIC_VARIABLE COMPARISON_OPERATOR numeric_value -> numeric_pair
    | MANA_VARIABLE COMPARISON_OPERATOR mana_value -> mana_pair
    | UNCOMPARABLE_STRING_VARIABLE ":" string_value -> uncomparable_string_pair

?string_value : SHORT_LITERAL | LONG_LITERAL | REGEX_VALUE

?numeric_value : INTEGER | NUMERIC_VARIABLE

?mana_value : INTEGER | mana_expression

mana_expression : MANA_SYMBOL+

LONG_LITERAL.10 : /"[^"]+"/

OR.9 : " OR " | " or "

AND.9 : " AND " | " and " | " && "

LPAREN.9 : "("

RPAREN.9 : ")"

SHORT_LITERAL.-1 : /[^\/\s:<>!="()][^\s:<>!="()]*/

REGEX_VALUE : /\/(?:\\\/|[^\/])+\//

NEGATION_OPERATOR : "-"
