apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../prod
namespace: spellbook-dev
patches:
  - patch: |-
      - op: replace
        path: "/subjects/0/name"
        value: "spellbook-admins-dev"
    target:
      kind: RoleBinding
      name: spellbook-rolebinding
