---
apiVersion: v1
kind: Namespace
metadata:
  name: spellbook-reddit-bot-prod
  labels:
    elbv2.k8s.aws/pod-readiness-gate-inject: enabled
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: spellbook-reddit-bot-prod
  name: spellbook-reddit-bot
  labels:
    app: spellbook-reddit-bot
spec:
  selector:
    matchLabels:
      app: spellbook-reddit-bot
  template:
    metadata:
      labels:
        app: spellbook-reddit-bot
    spec:
      serviceAccountName: app-service-account
      containers:
        - name: spellbook-reddit-bot-app
          image: 083767677168.dkr.ecr.us-east-2.amazonaws.com/spellbook-prod-reddit-ecr
          ports:
            - containerPort: 80
          livenessProbe:
            exec:
              command:
                - wget
                - --output-document=/dev/null
                - --quiet
                - https://backend.commanderspellbook.com
            initialDelaySeconds: 40
            periodSeconds: 20
            timeoutSeconds: 5
          env:
            - name: REDDIT_USERNAME
              valueFrom:
                secretKeyRef:
                  name: reddit-bot-secrets
                  key: reddit-username
            - name: REDDIT_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: reddit-bot-secrets
                  key: reddit-password
            - name: REDDIT_CLIENT_ID
              valueFrom:
                secretKeyRef:
                  name: reddit-bot-secrets
                  key: reddit-client-id
            - name: REDDIT_CLIENT_SECRET
              valueFrom:
                secretKeyRef:
                  name: reddit-bot-secrets
                  key: reddit-client-secret
            - name: SPELLBOOK_API_URL
              value: https://backend.commanderspellbook.com
            - name: SPELLBOOK_WEBSITE_URL
              value: https://commanderspellbook.com
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: app-service-account
  namespace: spellbook-reddit-bot-prod
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::083767677168:role/spellbook-application-role
